Discipline Priest Checklist
WoWAnalyzer/WoWAnalyzer pull request #1896
Opened 2018-07-15 23:13 UTC by rp4rk

* Minor change to the rule styling to enforce a visual hierarchy.

[New](https://user-images.githubusercontent.com/8212881/42739294-ae5e77b8-888c-11e8-96de-0b39eb7583a9.png)
[Old](https://user-images.githubusercontent.com/8212881/42739309-f3993458-888c-11e8-9586-5b78310cd3c1.png)

* Basics for the discipline checklist

2018-07-15 23:16 UTC, TravisBuddy commented
## Travis tests have failed

Hey @rp4rk,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### Node.js: 10.4


<details>
  <summary>
    <strong>
     npm run lint -- --max-warnings&#x3D;0
    </strong>
  </summary>

```
> WoWAnalyzer@ lint /home/travis/build/WoWAnalyzer/WoWAnalyzer
> eslint . "--max-warnings=0"


/home/travis/build/WoWAnalyzer/WoWAnalyzer/src/Parser/Priest/Discipline/Modules/Features/Checklist/Component.js
  5:8  warning  'ITEMS' is defined but never used     no-unused-vars
  7:8  warning  'ItemLink' is defined but never used  no-unused-vars

✖ 2 problems (0 errors, 2 warnings)

ESLint found too many warnings (maximum: 0).
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! WoWAnalyzer@ lint: `eslint . "--max-warnings=0"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the WoWAnalyzer@ lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-07-15T23_15_20_958Z-debug.log
```

</details>

2018-07-16 18:08 UTC, MartijnHols requested changes
The checklist looks really good! The only blocker is the layout changes.

2018-07-16 19:10 UTC, rp4rk commented on src/Parser/Priest/Discipline/Modules/Features/Checklist/Component.js
> +              Cooldowns are an important part of healing, try to use them to counter fight mechanics. For example if a boss has burst damage each 1.5 minutes, <SpellLink id={SPELLS.RAPTURE.id} /> sho
I'd tend to say each but every reads better here :D

2018-07-16 19:10 UTC, rp4rk commented on src/Parser/Priest/Discipline/Modules/Features/Checklist/Component.js
> +          {combatant.hasTalent(SPELLS.SCHISM_TALENT.id) && (
Yeah already tried that, better off with this for now I think.

2018-07-16 19:11 UTC, rp4rk commented on src/Parser/Core/Modules/Features/Checklist2/Rule.js
> +                <InformationIcon style={{ position: 'absolute', top: 15, left: 18, fontSize: '2em' }} />
I'll get it lined up

2018-07-21 15:51 UTC, TravisBuddy commented
## Travis tests have failed

Hey @rp4rk,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### Node.js: 10.4


<details>
  <summary>
    <strong>
     npm run test -- --maxWorkers&#x3D;2
    </strong>
  </summary>

```
> WoWAnalyzer@ test /home/travis/build/WoWAnalyzer/WoWAnalyzer
> react-scripts test --env=jsdom "--maxWorkers=2"

 PASS  src/Parser/Druid/Feral/Modules/Normalizers/ComboPointsFromAoE.test.js
 PASS  src/Parser/Core/Modules/SpellUsable.test.js (14.425s)
 PASS  src/Parser/Core/CombatLogParser.test.js (9.859s)
 PASS  src/Parser/Druid/Feral/Modules/Normalizers/RakeBleed.test.js
 PASS  src/Parser/Paladin/Holy/Normalizers/LightOfDawn.test.js
 PASS  src/Parser/Core/Analyzer.test.js
 PASS  src/Parser/Paladin/Holy/Normalizers/BeaconOfVirtue.test.js
 PASS  src/Parser/Druid/Restoration/Normalizers/WildGrowth.test.js
 PASS  src/common/stats.test.js
 PASS  src/Parser/Core/Modules/Features/Checklist/performanceForThresholds.test.js
 PASS  src/Parser/Core/Modules/Features/Checklist2/helpers/performanceForThresholds.test.js
 PASS  src/Parser/Priest/Discipline/Normalizers/AtonementSuccessiveDamage.test.js
 PASS  src/Parser/Monk/Brewmaster/Modules/Spells/BlackoutCombo.test.js
 PASS  src/Interface/Others/ReportSelector.test.js
 PASS  src/Parser/Monk/Brewmaster/Modules/Core/HealingDone.test.js
 PASS  src/Parser/Core/Modules/Abilities.test.js
 PASS  src/Parser/Monk/Brewmaster/Modules/Core/DamageTaken.test.js
 PASS  src/Parser/Shaman/Restoration/Modules/Spells/HealingRain.test.js
 FAIL  src/Parser/Priest/Discipline/SpellCalculations.test.js
  ● [PENANCE] Spell Calculations › Estimates Offensive Penance Bolts Correctly

    expect(received).toEqual(expected)
    
    Expected value to equal:
      {"boltDamage": 40, "boltHealing": 16}
    Received:
      {"boltDamage": 40, "boltHealing": 24}
    
    Difference:
    
    - Expected
    + Received
    
     Object {
       "boltDamage": 40,
    -  "boltHealing": 16,
    +  "boltHealing": 24,
     }
      
      at Object.it (src/Parser/Priest/Discipline/SpellCalculations.test.js:33:29)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  ● [PENANCE] Spell Calculations › Estimates Offensive Penance Bolts Correctly with Versatility

    expect(received).toEqual(expected)
    
    Expected value to equal:
      {"boltDamage": 50, "boltHealing": 20}
    Received:
      {"boltDamage": 50, "boltHealing": 30}
    
    Difference:
    
    - Expected
    + Received
    
     Object {
       "boltDamage": 50,
    -  "boltHealing": 20,
    +  "boltHealing": 30,
     }
      
      at Object.it (src/Parser/Priest/Discipline/SpellCalculations.test.js:42:29)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  ● [SMITE] Spell Calculations › Estimates Smites Correctly

    expect(received).toEqual(expected)
    
    Expected value to equal:
      {"smiteDamage": 75, "smiteHealing": 30}
    Received:
      {"smiteDamage": 75, "smiteHealing": 45}
    
    Difference:
    
    - Expected
    + Received
    
     Object {
       "smiteDamage": 75,
    -  "smiteHealing": 30,
    +  "smiteHealing": 45,
     }
      
      at Object.it (src/Parser/Priest/Discipline/SpellCalculations.test.js:53:30)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  ● [SMITE] Spell Calculations › Estimates Smites Correctly with Versatility

    expect(received).toEqual(expected)
    
    Expected value to equal:
      {"smiteDamage": 94, "smiteHealing": 38}
    Received:
      {"smiteDamage": 94, "smiteHealing": 56}
    
    Difference:
    
    - Expected
    + Received
    
     Object {
       "smiteDamage": 94,
    -  "smiteHealing": 38,
    +  "smiteHealing": 56,
     }
      
      at Object.it (src/Parser/Priest/Discipline/SpellCalculations.test.js:62:30)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:68:7)

 PASS  src/Parser/Monk/Brewmaster/Modules/Core/Stagger.test.js
 PASS  src/Interface/Others/Report/PlayerSelectionList.test.js
 PASS  src/Interface/common/CyclingVideo.test.js
 PASS  src/common/format.test.js
 PASS  src/Parser/Druid/Guardian/Modules/Features/Gore.test.js
 PASS  src/Parser/Core/EventGrouper.test.js
 PASS  src/Parser/Core/Modules/Ability.test.js
 PASS  src/Parser/Priest/Discipline/Modules/Items/Tier21_2set.test.js
 PASS  src/Parser/Core/Modules/Helpers/CritEffectBonus.test.js
 PASS  src/Parser/Monk/Brewmaster/Modules/Spells/IronskinBrew.test.js
 PASS  src/Parser/Core/calculateEffectiveHealing.test.js
 PASS  src/Parser/Druid/Guardian/Modules/Spells/IronFur.test.js
 PASS  src/Parser/Druid/Guardian/Modules/Features/GuardianOfElune.test.js
 PASS  src/Parser/Core/Combatant.test.js
 PASS  src/Parser/Mage/Shared/Modules/Items/ShardOfTheExodar.test.js
 PASS  src/Parser/Monk/Brewmaster/Modules/Items/T20_4pc.test.js
 PASS  src/Interface/Premium/index.test.js
 PASS  src/Interface/Premium/LoginPanel.test.js
 PASS  src/Parser/Monk/Brewmaster/Modules/Spells/RushingJadeWind.test.js
 PASS  src/tests/CHANGELOG.test.js
 PASS  src/Parser/Core/Modules/Features/Checklist2/helpers/calculateMedian.test.js
 PASS  src/Parser/Core/Modules/Features/Checklist/calculateMedian.test.js
 PASS  src/Interface/common/ReadableList.test.js
 PASS  src/Parser/Monk/Brewmaster/Modules/Items/T20_2pc.test.js
 PASS  src/common/parseVersionString.test.js
 PASS  src/Interface/Contributor/Details.test.js
(node:3408) UnhandledPromiseRejectionWarning: Error: Cannot find module '@lingui/loader!Localization/en/messages.json' from 'LocalizationLoader.js'
    at Resolver.resolveModule (/home/travis/build/WoWAnalyzer/WoWAnalyzer/node_modules/wowanalyzer-react-scripts/node_modules/jest-resolve/build/index.js:179:17)
    at Resolver._getVirtualMockPath (/home/travis/build/WoWAnalyzer/WoWAnalyzer/node_modules/wowanalyzer-react-scripts/node_modules/jest-resolve/build/index.js:296:23)
    at Resolver._getAbsolutPath (/home/travis/build/WoWAnalyzer/WoWAnalyzer/node_modules/wowanalyzer-react-scripts/node_modules/jest-resolve/build/index.js:279:10)
    at Resolver.getModuleID (/home/travis/build/WoWAnalyzer/WoWAnalyzer/node_modules/wowanalyzer-react-scripts/node_modules/jest-resolve/build/index.js:252:31)
    at Runtime._shouldMock (/home/travis/build/WoWAnalyzer/WoWAnalyzer/node_modules/wowanalyzer-react-scripts/node_modules/jest-runtime/build/index.js:574:37)
    at Runtime.requireModuleOrMock (/home/travis/build/WoWAnalyzer/WoWAnalyzer/node_modules/wowanalyzer-react-scripts/node_modules/jest-runtime/build/index.js:402:14)
    at Promise.resolve.then (/home/travis/build/WoWAnalyzer/WoWAnalyzer/src/Interface/LocalizationLoader.js:28:56)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3408) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 PASS  src/Root.test.js (11.032s)

Summary of all failing tests
 FAIL  src/Parser/Priest/Discipline/SpellCalculations.test.js
  ● [PENANCE] Spell Calculations › Estimates Offensive Penance Bolts Correctly

    expect(received).toEqual(expected)
    
    Expected value to equal:
      {"boltDamage": 40, "boltHealing": 16}
    Received:
      {"boltDamage": 40, " [...]

2018-07-21 16:29 UTC, rp4rk commented on src/Parser/Core/Modules/Features/Checklist2/Rule.js
> +          <div className="details" style={{ display: this.state.expanded ? undefined : 'none', paddingLeft: 65, position: 'relative', minHeight: 80 }}>
Optimizing for readability, the icon is definitely not something I'd consider readable content. I'd consider the information icon to be there as anchorage for scanning, letting people know that this is content that is providing useful information.

2018-07-21 16:41 UTC, MartijnHols approved these changes

2018-07-21 16:57 UTC, merged