[Core] Move Stat constants out of StatTracker
WoWAnalyzer/WoWAnalyzer pull request #3846
Opened 2020-10-09 16:04 UTC by anontyro

Split out the static objects into there own file along with slight renaming and fixing the statTracker. Let me know if there is anything that needs updating here

#3835

2020-10-09 16:26 UTC, Dambroda commented
I'm not sure if this is something we want to do. I'll leave it up for some other opinions. But this also broke some integration tests so that would need to be resolved beforehand.

2020-10-09 16:29 UTC, Pewtro commented
So the reason I made the issue was when I was adjusting StatTracker for the Diminishing Returns and got annoyed with the fact we were defining all those default buffs in there - that said we almost never work in that file so maybe it's fine. 

In theory I'm /care either way.

2020-10-10 12:27 UTC, anontyro commented
so I've fixed the problems the integration tests had, I think it does work to pull out some of the larger objects, I guess it also depends on how much these objects grow overtime aswell

2020-10-12 16:55 UTC, emallson requested changes

2020-10-12 16:55 UTC, emallson commented on src/parser/shared/modules/StatTracker.js
> -  statMultiplier = {
`statMultiplier` is an internal object for `StatTracker`, not a buff list. It should stay in StatTracker. the other stuff seems fine.

2020-10-29 19:37 UTC, emallson commented on src/parser/shared/modules/StatTracker.js
> -  statMultiplier = {
@anontyro just checking in. are you planning to follow up on this PR?

2020-11-07 01:45 UTC, Pewtro commented
Closing this due to inactivity.

2020-11-07 01:45 UTC, closed without merging