[Shadowlands][Disc Priest] Added Covenent Ability Boon of the Ascended.
WoWAnalyzer/WoWAnalyzer pull request #3851
Opened 2020-10-10 09:32 UTC by Ogofo

Hello,

this is my first PR on this proejct. I implemented the covenen module Boon of the Ascended for discipline priests. It seems to work, however I am unsure how I can further test and ensure the logic/parsing is correct. 

If you have any comments on this or the code alongside with recommendations, feel free to message me (either on discord: Ogofo, or here).

I wanted to thank @karlpralow, as he explained the basics to me :)

2020-10-10 09:35 UTC, Pewtro commented
You should test it on a beta log that uses that ability to verify it works as it should. 

We have a CombatantInfoFaker file that you can fill info into to 'force' in the covenant being detected for the purpose of activating the module.

2020-10-10 09:38 UTC, Pewtro commented on src/parser/priest/discipline/CHANGELOG.tsx
>    change(date(2020, 10, 3), <>Update <SpellLink id={SPELLS.POWER_WORD_SOLACE_TALENT.id} /> cooldown.</>, [Reglitch]),
Capital M should be lowercased

2020-10-10 09:46 UTC, Pewtro requested changes
Some things that you should change that will make it much more readable (and match the current codebase standards)

If I misunderstood how the atonement works, do say so - but from initial look it should work just fine.

2020-10-10 09:46 UTC, Pewtro commented on src/parser/priest/discipline/modules/shadowlands/covenants/BoonOfTheAscended.tsx
> +
You should filter it down to blast, Nova and Eruption in the eventListener. 
```js
this.addEventListener(Events.heal.by(SELECTED_PLAYER).spell([SPELLS.ASCENDED_BLAST, SPELLS.ASCENDED_NOVA, SPELLS.ASCENDED_ERUPTION])
```

2020-10-10 09:46 UTC, Pewtro commented on src/parser/priest/discipline/modules/shadowlands/covenants/BoonOfTheAscended.tsx
> +  }
the entire onHeal should be rewritten after the eventlistener has been updated to be 
```js
onHeal(event: HealEvent) {
  if (isAtonement(event)) {

      const atonenementDamageEvent = this.atonementDamageSource.event;

      if (!atonenementDamageEvent) {
        return;
      }
      this.atonementHealing += event.amount + (event.absorbed || 0);
  } else {
    this.directHealing += event.amount + (event.absorbed || 0);
}
```

2020-10-10 14:02 UTC, Ogofo commented
@Pewtro Thanks for the help! Appreciated.
I implemented your suggestions. 

I tested the module with a [Disc-Priest beta log](https://www.warcraftlogs.com/reports/qrjaTbWKdHfx6Jcy#fight=25). It seems consistent. 

What's missing is that the icons are correctly displayed - however I cannot seem to find where to link/reference the correct icon art. Could you point me there?

2020-10-10 14:06 UTC, Pewtro approved these changes

2020-10-10 14:06 UTC, Pewtro commented
So long as the icon is correctly added in the spell object (it looks to be), it'll work just fine when wowhead switches over. 
(They might exist only on shadowlands.wowhead.com)

2020-10-11 20:28 UTC, Pewtro commented
Thanks for the PR!

2020-10-11 20:28 UTC, merged