Convert Boring Components to TypeScript
WoWAnalyzer/WoWAnalyzer pull request #3964
Opened 2020-10-20 03:07 UTC by Khazakdk

Converted a few additional related files while I was at it.  Tagging rogue specifically for this PR because I had to modify a couple files that were using the resource lookup and want to make sure the changes are sane. @darthelit

2020-10-20 11:49 UTC, darthelit commented
Looks good. Doesn't seem like anything SHOULD be affected by the change and rogue should still work without having `undefined` returned.

2020-10-20 11:50 UTC, darthelit approved these changes

2020-10-20 13:57 UTC, MartijnHols requested changes

2020-10-20 13:57 UTC, MartijnHols commented on src/parser/rogue/outlaw/modules/talents/BladeRush.tsx
> +    if (!event.classResources || !getResource(event.classResources!, RESOURCE_TYPES.COMBO_POINTS.id)) {
```suggestion
    if (!event.classResources || !getResource(event.classResources, RESOURCE_TYPES.COMBO_POINTS.id)) {
```

The first check should already tell TS that event.classResources now no longer can be undefined.

2020-10-20 15:03 UTC, tyndivelspaz commented on src/parser/rogue/outlaw/modules/talents/BladeRush.tsx
> +    if (!event.classResources || !getResource(event.classResources!, RESOURCE_TYPES.COMBO_POINTS.id)) {
Good catch. I need to get out if JS mode and into TS mode to catch things like this when reviewing.

2020-10-20 15:56 UTC, Khazakdk commented on src/parser/rogue/outlaw/modules/spells/BladeFlurry.ts
> +    if (!event.classResources || !getResource(event.classResources!, RESOURCE_TYPES.COMBO_POINTS.id)) {
```suggestion
    if (!event.classResources || !getResource(event.classResources, RESOURCE_TYPES.COMBO_POINTS.id)) {
```

2020-10-21 22:54 UTC, Pewtro commented
Looks good to me, thanks!

2020-10-21 22:55 UTC, merged