[Priest] Boon of the Ascended
WoWAnalyzer/WoWAnalyzer pull request #4290
Opened 2020-12-29 05:31 UTC by TJMoats

This module was already built for Disc, but it straight didn't work. I've fixed it and expanded it to Holy and Shadow.

Disc: 
<img width="462" alt="Screen+Shot+2020-12-28+at+11 23 00+PM" src="https://user-images.githubusercontent.com/716498/103260838-bd837b80-4964-11eb-937c-ae9178389f01.png">

Holy: 
<img width="444" alt="Screen+Shot+2020-12-28+at+11 23 16+PM" src="https://user-images.githubusercontent.com/716498/103260839-c07e6c00-4964-11eb-8a9d-4a06ac638373.png">

Shadow: 
<img width="442" alt="Screen+Shot+2020-12-28+at+11 23 34+PM" src="https://user-images.githubusercontent.com/716498/103260843-c2e0c600-4964-11eb-8355-46c4da0eebb6.png">

2020-12-29 05:33 UTC, TJMoats commented on src/parser/core/Entity.ts
> +  getBuffStacks(spellId: number, forTimestamp: number | null = null, bufferTime = 0, minimalActiveTime = 0, sourceID: number | null = null) {
I think that this is kinda useful, if anyone feels otherwise, I'm happy to remove this.

2020-12-29 18:38 UTC, DylanDirlam requested changes
Did not have time to do Night Fae/Venthyr but just some minor things

2020-12-29 18:38 UTC, DylanDirlam commented on src/parser/priest/holy/modules/Abilities.ts
> +        enabled: combatant.hasCovenant(COVENANTS.NIGHT_FAE.id),
This one needs a 1.5s GCD too

2020-12-29 18:38 UTC, DylanDirlam commented on src/parser/priest/holy/modules/Abilities.ts
> +        spell: SPELLS.ASCENDED_BLAST,
Looks like this ability has a 1s GCD https://www.wowhead.com/spell=325283/ascended-blast

2020-12-29 18:38 UTC, DylanDirlam commented on src/parser/priest/holy/modules/Abilities.ts
> +        spell: SPELLS.ASCENDED_NOVA,
1s gcd as well https://www.wowhead.com/spell=325020/ascended-nova

2020-12-29 18:38 UTC, DylanDirlam commented on src/parser/priest/shadow/modules/Abilities.tsx
> +        spell: SPELLS.ASCENDED_BLAST,
1s gcd

2020-12-29 18:38 UTC, DylanDirlam commented on src/parser/priest/shadow/modules/Abilities.tsx
> +        spell: SPELLS.ASCENDED_NOVA,
1s gcd

2020-12-29 18:38 UTC, DylanDirlam commented on src/parser/priest/shared/modules/shadowlands/covenants/BoonOfTheAscended.tsx
> +    this.ascendedSpellTracker[event.ability.guid].damageDone += event.amount + (event.absorb || 0);
The `event.absorb` should be `event.absorbed`

2020-12-29 18:38 UTC, DylanDirlam commented on src/parser/priest/shared/modules/shadowlands/covenants/BoonOfTheAscended.tsx
> +          </td>
Looking at the screenshot at first, I couldn't tell what the green and red numbers meant. I thought the green was targets hit and red was misses but that didn't make sense. Maybe a tooltip can be added to the column label?

2020-12-29 18:38 UTC, DylanDirlam commented on src/parser/priest/discipline/modules/Abilities.ts
> +        spell: SPELLS.ASCENDED_BLAST,
1s gcd, see other comment below

2020-12-29 18:38 UTC, DylanDirlam commented on src/parser/priest/discipline/modules/Abilities.ts
> +        spell: SPELLS.ASCENDED_NOVA,
1s gcd

2021-01-01 04:46 UTC, TJMoats commented on src/parser/priest/shared/modules/shadowlands/covenants/BoonOfTheAscended.tsx
> +          </td>
Tooltip added!

2021-01-04 04:21 UTC, TJMoats commented on src/parser/priest/holy/modules/Abilities.ts
> -        spell: SPELLS.UNHOLY_NOVA,
I'm moving this to the module to match the other covs

2021-01-04 04:21 UTC, TJMoats commented on src/parser/priest/holy/modules/Abilities.ts
> +        spell: SPELLS.POWER_WORD_SHIELD,
This was missing, so I'm just adding it as part of the rest of the work.

2021-01-04 04:22 UTC, TJMoats commented on src/parser/priest/shadow/modules/Abilities.tsx
> -        spell: SPELLS.BOON_OF_THE_ASCENDED,
Moving each of these to the modules

2021-01-20 18:24 UTC, merged