EventOrderNormalizer
WoWAnalyzer/WoWAnalyzer pull request #4475
Opened 2021-04-21 03:36 UTC by kfinch

We have like a dozen normalizers all of which do 'order enforcement' for specific simultaneous events and all of which have virtually copy-pasted code. I've moved that code into a single abstract 'EventOrderNormalizer', and made all the other normalizers extend it.

2021-04-21 03:39 UTC, kfinch commented on src/parser/core/EventOrderNormalizer.ts
> +  // FIXME should we also check target instance?
The RakeBleed normalizer matches targetInstance in addition to targetID... does anyone know why? Does anyone know when this is relevant?

2021-04-21 12:57 UTC, kfinch commented on src/parser/core/EventOrderNormalizer.ts
> +  // FIXME should we also check target instance?
I figured it out, adds may have same targetID and must be discerned by different targetInstance. I added baseline targetInstance support to the normalizer.

2021-04-24 19:52 UTC, rp4rk requested changes
Kino work, need some unit tests I think for a little confidence before merge. Particularly around the EventOrderNormalizer.

2021-04-26 11:22 UTC, rp4rk approved these changes

2021-04-26 11:27 UTC, merged