German interface translations
WoWAnalyzer/WoWAnalyzer pull request #4476
Opened 2021-04-25 01:08 UTC by maestrohdude

2021-05-01 19:32 UTC, sLaiN1 requested changes
Thank you a lot for your help, it is really appreciated! I added some comments about stuff I found.  Please excuse me, if it happens to be a bit nitpicky. 

It's a lot of work you put in there.

2021-05-01 19:32 UTC, sLaiN1 commented on src/localization/de/messages.json
> +  "druid.resto.suggestions.innervate.selfCasts": "Wieviele Male, dass du Anregen an dir selbst eingesetzt hast",
![image](https://user-images.githubusercontent.com/36763177/116792275-e73de200-aabf-11eb-849a-934676b20d69.png)

Der Kontext lässt sich in der englischen Version schlecht fassen, ohne das Beispiel zu sehen. Dadurch ist der Satz etwas unlogisch geraten.

Vielleicht `mal Anregen auf dich selbst eingesetzt`

2021-05-01 19:32 UTC, sLaiN1 commented on src/localization/de/messages.json
> +  "interface.premiumPage.unlocks.new": "<0>Neue Sachen</0><1>Nichts entwickelt sich selbst.</1> Deine Einträge werden neue Sachen und Verbesserungen für die Website fundieren, dass sie noch besser wi
'fundieren' würde ich an der Stelle mit 'finanzieren' übersetzen, der Satz klingt so etwas sperrig.
Ein weiterer Formulierungsvorschlag wäre 'dass' mit 'sodass zu ersetzen.

Mit 'contribution' sind eher Beiträge (finanzielle Beiträge) gemeint. Eine beispielhafte Übersetzung wäre:
`Deine Beiträge helfen neue Sachen und Verbesserungen für die Webseite zu finanzieren, sodass sie noch besser wird.`

2021-05-01 19:32 UTC, sLaiN1 commented on src/localization/de/messages.json
> +  "interface.report.fightSelection.fightSelectionDetails": "Wähle den Kampf aus, den du analysieren möchtest. Wenn ein Boss oder Kampf fehlt, oder die Liste nach unten leer ist, drücke den 'Neu laden
'press the Refresh button above' -> Damit ist gemeint, dass der Knopf über dem Text ist, also eher
`drücke den "Neu laden" oben`

2021-05-01 19:32 UTC, sLaiN1 commented on src/localization/de/messages.json
> +  "interface.report.patchChecker.viewAnalysisOldExpansion": "Wegen der Menge Klassenänderungen seit der letzten Erweiterung (Klassenfähigkeiten, Talente, usw.), wird die von WoWAnalyzer gebotene Anal
"Du kannst immerhin der Analyse zugreifen" liest sich etwas unangenehm. 
`Du kannst weiterhin auf die Analyse zugreifen, [...]`

Hier soll 'below' auch bedeuten, dass der Knopf unter dem Text ist, somit eher:
`indem du unten auf "Trotzdem fortfahren" klickst [...]`

2021-05-01 19:32 UTC, sLaiN1 commented on src/localization/de/messages.json
> +  "interface.report.patchChecker.viewAnalysisOnOlderVersion": "WoWAnalyzer wird ständig aktualisiert, um die neuesten Änderungen zu unterstützen. Das kann zur Entfernung oder Änderung einiger Funktio
'below' -> `kannst du unten auf "Trotzdem fortfahren" klicken.`

2021-05-01 23:22 UTC, maestrohdude commented on src/localization/de/messages.json
> +  "interface.premiumPage.unlocks.new": "<0>Neue Sachen</0><1>Nichts entwickelt sich selbst.</1> Deine Einträge werden neue Sachen und Verbesserungen für die Website fundieren, dass sie noch besser wi
Ich war ja bezüglich dem Beitrag gegen Eintrag Ding eher unsicher. Danke der Erklärung!

2021-05-04 16:03 UTC, kfinch commented
SLaiN seemed positive on this but is probably busy with his thesis. I'm going to assume the followups resolved the issues and just get this in.

2021-05-04 16:03 UTC, merged