[Rogue] Add CD efficiency and follow-up ability tracking for Sepsis
WoWAnalyzer/WoWAnalyzer pull request #4477
Opened 2021-04-25 17:25 UTC by hpabst

### Notes
- Add CD efficiency tracking to Sepsis analyzer.
- Add CD reduction tracking to Sepsis analyzer.
- Add new analyzer, `StealthAbilityFollowingSepsis` to track proper stealth ability usage following Sepsis DoT completion.

### Screenshots:
![image](https://user-images.githubusercontent.com/6363390/116002810-44adcc80-a5b0-11eb-85a5-e73675501348.png)
![image](https://user-images.githubusercontent.com/6363390/116002826-52635200-a5b0-11eb-9b71-2e97e80bca8e.png)
![image](https://user-images.githubusercontent.com/6363390/116002840-5ee7aa80-a5b0-11eb-9e69-78b3b3ff860a.png)

2021-04-25 17:26 UTC, hpabst commented
For reference, these logs were used in testing:

https://www.warcraftlogs.com/reports/q2TQCpfX3KB7trFY#fight=6&type=damage-done&source=14
https://www.warcraftlogs.com/reports/HRN6fDc7bnATqwL1#fight=77&type=damage-done&source=746
https://www.warcraftlogs.com/reports/XybvWxgnZBPzwHFV#fight=18&type=damage-done&source=149

2021-04-27 13:38 UTC, kfinch requested changes
Overall looks good, just a couple comments.

2021-04-27 13:38 UTC, kfinch commented on analysis/rogue/src/covenants/nightfae/Sepsis.tsx
> +    }
Can skip this check by adding a `by` check to the EventListener, like is already present on the other event listeners.

2021-04-27 13:38 UTC, kfinch commented on analysis/rogue/src/covenants/nightfae/StealthAbilityFollowingSepsis.tsx
> +  }
Am I correctly reading that this will show even if you have zero bad casts? It might look a little confusing in that case.

2021-04-27 20:51 UTC, darthelit commented on analysis/rogue/src/covenants/nightfae/StealthAbilityFollowingSepsis.tsx
> +  }
I don't think hiding this on 0 bad casts would be beneficial. I'd like to think that seeing I had 0 bad casts would give immediate positive reinforment.

2021-04-28 12:53 UTC, kfinch commented on analysis/rogue/src/covenants/nightfae/StealthAbilityFollowingSepsis.tsx
> +  }
I guess I was thinking the tooltip would be weird, but I suppose you're right. It's up to @hpabst to change or leave as is.

2021-04-29 17:16 UTC, darthelit approved these changes
All looks good to me. You can address the tooltip comment or leave it be. I think it can go either way

2021-04-30 03:16 UTC, hpabst commented on analysis/rogue/src/covenants/nightfae/Sepsis.tsx
> +    }
Will resolve in the next revision.

2021-04-30 03:17 UTC, hpabst commented on analysis/rogue/src/covenants/nightfae/StealthAbilityFollowingSepsis.tsx
> +  }
I agree in that the tooltip could be kind of weird along with the dropdown if there are 0 bad casts. I'll adjust this in the next revision to remove the dropdown and have a different tooltip if there are 0 bad casts.

2021-05-01 14:07 UTC, kfinch approved these changes
noice

2021-05-01 14:07 UTC, merged