Localization and TS updates
WoWAnalyzer/WoWAnalyzer pull request #4626
Opened 2021-10-13 19:33 UTC by ckaczor

- Convert Armory icon file from JS to TSX
- Localization in Armory icon file
- Localization of Armory text

A first round of changes to make sure I'm on the right track.  I'll do more (in small-ish batches) once this is approved.

2021-10-13 22:49 UTC, emallson requested changes
Good start! Would appreciate using a type for the `Icon` props instead of `any`.

Also: are there uses of the `<ArmoryIcon />` component that *aren't* immediately followed by the ` Armory` text? if not it may make sense to make a shortcut since the `Trans` version is a little more involved. That doesn't need to be in this PR though.

2021-10-13 22:49 UTC, emallson commented on src/interface/icons/Armory.tsx
> +const Icon = (props: any) => (
when typing a wrapper component like this, you should use something like:

```suggestion
type Props = Omit<React.ComponentPropsWithoutRef<'img'>, "src" | "alt" | "className">;
const Icon = (props: Props) => (
```

that way users of the icon get direct typechecking support

2021-10-14 01:36 UTC, ckaczor commented on src/interface/icons/Armory.tsx
> +const Icon = (props: any) => (
Thanks for the feedback - I just pushed a change with proper typing.

It looks like DEFAULT_BUILD.tsx uses ArmoryIcon without any text afterwards.  I'm not quite sure what you mean by shortcut - I'm pretty new to React so maybe that's something I haven't come across yet.

Thanks!

2021-10-14 04:52 UTC, emallson commented on src/interface/icons/Armory.tsx
> +const Icon = (props: any) => (
By a shortcut i just meant a component that had the text and `<Trans>...</Trans>` element as part of the output, but since it is sometimes used without that part it doesn't need it. Thanks!

2021-10-14 04:52 UTC, emallson approved these changes

2021-10-14 04:52 UTC, merged