Small localization changes and another batch of basic TypeScript conversions/improvements
WoWAnalyzer/WoWAnalyzer pull request #4634
Opened 2021-10-18 17:37 UTC by ckaczor

Last batch of updates to the icons with some associated localization changes.

2021-10-18 22:24 UTC, emallson requested changes
Type changes look good. I don't believe the translation changes are needed because generally proper names don't get localized in this context. `interface.warcraftLogs.timeline` can get localized since it is more than just the name, but for now lets leave the `Trans` off of WCL/Wipefest.

2021-10-18 22:24 UTC, emallson commented on src/localization/en/messages.json
> +  "interface.wipefest": "Wipefest",
these are proper names so I don't believe that they get translated. the "timeline" part might, but checking the WCL website they don't translate their name on other language variants.

2021-10-19 00:00 UTC, ckaczor commented on src/localization/en/messages.json
> +  "interface.wipefest": "Wipefest",
Good point about the proper names - I've reverted the changes back to just TS changes and any localization (like "timeline") can come in another PR later.

2021-10-19 04:07 UTC, emallson approved these changes

2021-10-19 04:08 UTC, merged