Holy Paladin 4pc statistic
WoWAnalyzer/WoWAnalyzer pull request #4849
Opened 2022-04-09 03:26 UTC by xizbow1

2022-04-09 03:29 UTC, xizbow1 commented
![image](https://user-images.githubusercontent.com/93213703/162554705-dc55d5b3-25b8-42c6-a46a-6c9d4b1a1d05.png)

2022-04-09 03:46 UTC, abelito75 commented
imma review this. don't merge

2022-04-09 04:39 UTC, rp4rk approved these changes
I think this is as close as you can get to modelling the CDR, if it runs well against existing logs and gives sane numbers I think it's grand.

(LGTM)

2022-04-09 04:40 UTC, rp4rk commented on analysis/paladinholy/src/modules/shadowlands/tier/Tier28FourSet.tsx
> +  healing: number = 0;
Don't think you need healing/healingBoost/conduitRank etc. here, make sure to remove stuff when you're done with it :)

2022-04-09 04:51 UTC, abelito75 requested changes

2022-04-09 04:51 UTC, abelito75 commented on analysis/paladinholy/src/modules/shadowlands/tier/Tier28FourSet.tsx
> +            Effective Cooldown Reduction: {formatNumber(this.cooldownReductionUsed / 1000)} Seconds
Should use format duration instead of format number here

2022-04-09 04:51 UTC, abelito75 commented on analysis/paladinholy/src/modules/shadowlands/tier/Tier28FourSet.tsx
> +            Wasted Cooldown Reduction: {formatNumber(this.cooldownReductionWasted / 1000)} Seconds
same as above

2022-04-09 04:51 UTC, abelito75 commented on analysis/paladinholy/src/modules/shadowlands/tier/Tier28FourSet.tsx
> +            {formatNumber((120000 - this.cooldownReductionUsed / (this.WingsCasts + 1)) / 1000)}{' '}
same as above

2022-04-09 04:51 UTC, abelito75 commented on analysis/paladinholy/src/modules/shadowlands/tier/Tier28FourSet.tsx
> +
This file generally needs a listener for Wings casts to make sure we force reset its CD if its on CD when cast

2022-04-09 04:51 UTC, abelito75 commented on analysis/paladinholy/src/modules/shadowlands/tier/Tier28FourSet.tsx
> +  WingsCast(event: CastEvent) {
Please keep it camelCase

2022-04-09 04:51 UTC, abelito75 commented on analysis/paladinholy/src/modules/shadowlands/tier/Tier28FourSet.tsx
> +  LODheal(event: HealEvent) {
camelCase...

2022-04-09 04:51 UTC, abelito75 commented on analysis/paladinholy/src/modules/shadowlands/tier/Tier28FourSet.tsx
> +        <BoringSpellValueText spellId={SPELLS.DAWN_WILL_COME_4PC.id}>
This is a super long body of the stat
Might want to swap to a BoringValueText
so the title can encompass more of the body text
You can see an example of this in RenewingMistDuringManaTea

2022-04-11 16:04 UTC, abelito75 requested changes
idk maybe more later
Great track tho

2022-04-11 16:04 UTC, abelito75 commented on analysis/paladinholy/src/modules/shadowlands/tier/Tier28FourSet.tsx
> +import HealingDone from 'parser/shared/modules/throughput/HealingDone';
This isn't used at all. Remove

2022-04-11 16:04 UTC, abelito75 commented on analysis/paladinholy/src/modules/shadowlands/tier/Tier28FourSet.tsx
> +              Estimated Effective <SpellIcon id={SPELLS.DAWN_WILL_COME_4PC.id} /> Cooldown Reduction
Can probably simplify this to just
`<SpellIcon id={SPELLS.DAWN_WILL_COME_4PC.id} /> Average CDR of <SpellLink id={SPELLS.AVENGING_WRATH.id} />`

2022-04-16 03:57 UTC, abelito75 approved these changes

2022-04-16 03:57 UTC, merged