[Havoc DH] remove nemesis and fel mastery
WoWAnalyzer/WoWAnalyzer pull request #5004
Opened 2022-07-24 21:34 UTC by ToppleTheNun

remove talents that were removed in either BfA or Shadowlands prepatch.

2022-07-24 21:38 UTC, Pewtro requested changes
A minor thing - you don't have to create fragments (<> </>) when you're just writing text.

2022-07-24 21:38 UTC, Pewtro commented on analysis/demonhunterhavoc/src/CHANGELOG.tsx
> +  ),
```suggestion
  change(date(2022, 7, 24), 'Remove talents that were removed in Shadowlands.', ToppleTheNun),
```

2022-07-26 22:56 UTC, ToppleTheNun commented
@Pewtro This is ready for re-review whenever you're ready.

2022-07-26 22:57 UTC, Pewtro approved these changes
Looks good, thanks!

2022-07-26 22:57 UTC, merged