Enhancement/Resto Shaman - Elemental Blast talent
WoWAnalyzer/WoWAnalyzer pull request #5012
Opened 2022-07-27 08:16 UTC by djanse

The module for Elemental Blast was outdated and over complicated. These changes show the correct total uptime of the elemental blast buffs.

Elemental Blast also has a buff that increases the Haste by 3% this was added to the Haste module. In addition is structured the Haste module into class sections.

2022-07-28 02:38 UTC, emallson approved these changes
this will likely need a merge conflict resolution in the haste file because of other merged PRs

2022-07-28 07:06 UTC, djanse commented
I was quite sure it would too. Merge conflict has been resolved.

2022-07-31 20:38 UTC, HawkCorrigan requested changes

2022-07-31 20:38 UTC, HawkCorrigan commented on analysis/shaman/src/ElementalBlast.tsx
> +    return this.critUptime + this.hasteUptime + this.masteryUptime;
this doesnt work

2022-07-31 20:38 UTC, HawkCorrigan commented on analysis/shaman/src/ElementalBlast.tsx
> +    return this.critUptime + this.hasteUptime + this.masteryUptime;
you can have/will have multiple buffs at the same time so you cant just add the uptimes

2022-08-12 11:15 UTC, djanse commented
I'll close the PR since the fix is just a total buff uptime miscalculation shown in the statistic view. It however causes >100% uptime for elemental shaman.

2022-08-12 11:15 UTC, closed without merging