add support for tracking debuffs
WoWAnalyzer/WoWAnalyzer pull request #5020
Opened 2022-08-07 06:11 UTC by ToppleTheNun

create version of Buff/Buffs from #5019 specifically for
tracking debuffs. this is necessary for adding support
for the Fated Raid affixes.

I wanted to reuse the existing buff UI as I was unsure of
the value of adding a whole new UI style for the original
intended use of this functionality.

The alternative to this is to make the Timeline UI component
listen to the `ApplyDebuff`/`RemoveDebuff` events.

**Current Version of Debuff UI**
![Screenshot 2022-08-07 015942](https://user-images.githubusercontent.com/1672786/183277776-f8c2fa3f-d885-4496-91e1-6685f7fc4a90.png)

2022-08-09 13:16 UTC, kfinch reviewed
This has a lot of copy-paste from Buffs, maybe this should be even more tightly integrated with the existing Buffs module - do we even need a separate analyzer? Do we need a separate type for debuffs? Why not just include debuffs under the existing buffs structure, and update relevant listeners to include the additional event types?

I'd say don't change anything yet, I want more opinions on this.

2022-08-09 16:57 UTC, ToppleTheNun commented
> This has a lot of copy-paste from Buffs, maybe this should be even more tightly integrated with the existing Buffs module - do we even need a separate analyzer? Do we need a separate type for debuffs? Why not just include debuffs under the existing buffs structure, and update relevant listeners to include the additional event types?
> 
> I'd say don't change anything yet, I want more opinions on this.

I don't disagree; especially since this original case is for debuffs that are actually buffs. I think we'd still need some way to denote weird cases like these Fated infusions: currently handling it via `timelineBuff` on the `SpellbookDebuff` interface.

2022-08-10 00:50 UTC, emallson commented
> I don't disagree; especially since this original case is for debuffs that are actually buffs. I think we'd still need some way to denote weird cases like these Fated infusions: currently handling it via `timelineBuff` on the `SpellbookDebuff` interface.

definitely understandable, but probably best for everyone's sanity not to have two distinct but almost identical modules for `Buffs` and `Debuffs`. I see that it looks like you've started putting some debuff code in the Buffs module. Is the Debuffs module intended to be dead now?

2022-08-10 03:25 UTC, ToppleTheNun commented
> > I don't disagree; especially since this original case is for debuffs that are actually buffs. I think we'd still need some way to denote weird cases like these Fated infusions: currently handling it via `timelineBuff` on the `SpellbookDebuff` interface.
> 
> definitely understandable, but probably best for everyone's sanity not to have two distinct but almost identical modules for `Buffs` and `Debuffs`. I see that it looks like you've started putting some debuff code in the Buffs module. Is the Debuffs module intended to be dead now?
> 
> EDIT: if you want to make the name clear, you could rename it to 'Auras' as well, though I don't think that is necessary

The ones that are in there were added mostly to have a way to test the changes to buffs. I think I'll just have the one Buffs module add listen for ApplyDebuff and RemoveDebuff.

2022-08-12 02:07 UTC, emallson requested changes

2022-08-12 02:07 UTC, emallson commented on analysis/warriorfury/src/modules/features/Buffs.ts
>    buffs() {
this should be `auras()` now, correct?

2022-08-12 02:07 UTC, emallson commented on analysis/warriorprotection/src/modules/features/Buffs.ts
>    buffs() {
same

2022-08-12 02:07 UTC, emallson commented on analysis/druidferal/src/modules/Buffs.js
>    buffs() {
also this

2022-08-12 02:07 UTC, emallson commented on analysis/paladinretribution/src/modules/Buffs.js
>    buffs() {
and this

2022-08-12 02:09 UTC, emallson commented
looks like the refactoring tool missed the Buffs.js files in the conversion

2022-08-12 04:06 UTC, merged