expiation talent
WoWAnalyzer/WoWAnalyzer pull request #5105
Opened 2022-10-03 18:24 UTC by oisinod

2022-10-04 21:53 UTC, emallson requested changes
minor change to clean up the event listener, otherwise looks good :+1: 

(could merge without changing as well if you're pressed for time, its fairly nit-picky)

2022-10-04 21:53 UTC, emallson commented on src/analysis/retail/priest/discipline/modules/spells/Expiation.tsx
> +    this.addEventListener(Events.damage.by(SELECTED_PLAYER), this.onDamage);
```suggestion
    this.addEventListener(Events.damage.by(SELECTED_PLAYER).spell([
      SPELLS.EXPIATION_DAMAGE,
      TALENTS_PRIEST.SHADOW_WORD_DEATH_TALENT,
      SPELLS.MIND_BLAST
    ]), this.onDamage);
```

you should move the damage spell filter here. probably can't do that with the custom atonement stuff, but regular damage/healing events work

2022-10-04 21:53 UTC, emallson commented on src/analysis/retail/priest/discipline/modules/spells/Expiation.tsx
> +
```suggestion
```

this can then be removed, since the event listener will only be called for the listed spells.

2022-10-05 22:14 UTC, oisinod commented
@emallson Updated, didn't realise you can pass an array here. But the atonement one is a bit more difficult, yeah 😆

2022-10-05 22:17 UTC, merged