added pwr module
WoWAnalyzer/WoWAnalyzer pull request #5174
Opened 2022-10-16 11:38 UTC by oisinod

this will be used in the guide component

2022-10-16 20:53 UTC, djanse requested changes
Althought a bit confusing this seems to be working correctly.

2022-10-16 20:53 UTC, djanse commented on src/analysis/retail/priest/discipline/modules/spells/PowerWordRadiance.tsx
> +        return;
This return is unnecessary.

2022-10-16 20:53 UTC, djanse commented on src/analysis/retail/priest/discipline/modules/spells/PowerWordRadiance.tsx
> +  radAtones = 0;
Could you clear up the extra whitespaces?

2022-10-16 20:53 UTC, djanse commented on src/analysis/retail/priest/discipline/modules/spells/PowerWordRadiance.tsx
> +  lastPWR: CastEvent | null = null;
The above three properties seem to be unused. If you need to access them for the guide i'd suggest you store them together with the other data in `RadianceInfo`.

2022-10-16 20:53 UTC, djanse commented on src/analysis/retail/priest/discipline/modules/spells/PowerWordRadiance.tsx
> +
This module should only be active if the talent is chosen.

2022-10-18 16:57 UTC, oisinod commented
@djanse comments addressed :)

2022-10-18 17:07 UTC, djanse requested changes
Looks alot better :) Still a few changes that i'd like you to make.

2022-10-18 17:07 UTC, djanse commented on src/analysis/retail/priest/discipline/modules/spells/PowerWordRadiance.tsx
> +  radiancesOnAtonedTarget = 0;
Correct me if im wrong but i believe `radiancesOnAtonedTarget` can go too?

2022-10-18 17:07 UTC, djanse commented on src/analysis/retail/priest/discipline/modules/spells/PowerWordRadiance.tsx
> +
Could you still add an active check to the module?
```tsx
this.active = this.selectedCombatant.hasTalent(...);

if (!this.active) {
  return;
}
```

2022-10-18 17:12 UTC, oisinod commented on src/analysis/retail/priest/discipline/modules/spells/PowerWordRadiance.tsx
> +  radiancesOnAtonedTarget = 0;
👍

2022-10-18 17:13 UTC, oisinod commented
I didn't add the active thing because I thought it was a mandatory talent but you actually can avoid it even though it's on the second row 😆

2022-10-18 17:18 UTC, danny-janse approved these changes
Looks good now.

2022-10-18 17:21 UTC, merged