convert most of the report load process to FCs
WoWAnalyzer/WoWAnalyzer pull request #5260
Opened 2022-10-26 22:00 UTC by ToppleTheNun

2022-11-01 18:35 UTC, ToppleTheNun commented
@emallson I can pull the guide hooks over in this PR if you'd like to get it done at once or in a separate PR. It seems a bit like mixing of concerns, but I'll leave it up to you how you'd like to review the changes. I can also break this PR up.

2022-11-02 04:16 UTC, emallson requested changes
minor change (some kind of `isClassic` call) then this looks okay. gonna do more local testing

2022-11-02 04:16 UTC, emallson commented on src/interface/report/PlayerLoader.tsx
> +  ] = useReducer(fcReducer, defaultStateFC);
we do have redux in the codebase, but i don't think that is an adventure for today :upside_down_face:

2022-11-02 04:16 UTC, emallson commented on src/interface/report/PlayerLoader.tsx
> +  if (selectedReport.gameVersion === 2 || selectedReport.gameVersion === 3) {
this should use something more clear than checking if gameVersion is 2 or 3. This is actually checking `isClassic(selectedReport)` right? (I don't think that method exists)

2022-11-02 04:16 UTC, emallson commented on src/interface/report/PlayerLoader.tsx
> +      }
This should use some kind of `isClassic` check instead of checking bare gameVersion ids

2022-11-02 04:44 UTC, emallson approved these changes

2022-11-02 04:45 UTC, merged