Holy Priest: Updated divine word talent with new value
WoWAnalyzer/WoWAnalyzer pull request #5432
Opened 2022-11-24 22:52 UTC by emilnormann

Added missing functionality as well and fixed small typo.

2022-11-26 14:43 UTC, kfinch requested changes
I think I'm still not onboard with surfacing overhealing so prominently - I don't get the purpose of that for a heal like this.

2022-11-26 14:43 UTC, kfinch commented on src/analysis/retail/priest/holy/modules/talents/BottomRow/LightOfTheNaaru.tsx
> +          <small>Cooldown Reduction</small>
The 's' is the units, like "30s Cooldown Reduction" - why remove it?

2022-11-26 14:43 UTC, kfinch commented on src/analysis/retail/priest/holy/modules/talents/BottomRow/DivineWord.tsx
> +const ACTIVATOR_SPELL_INCREASE = 0.3;
The tooltip for Divine Word on wowhead currently shows 50% - is 30% the most up to date value?

2022-11-26 14:43 UTC, kfinch commented on src/analysis/retail/priest/holy/modules/talents/BottomRow/DivineWord.tsx
> +      this.chastiseDamage += calculateEffectiveDamage(event, DAMAGE_INCREASE_FROM_CHASTISE);
Shouldn't this be `ACTIVATOR_SPELL_INCREASE`?

2022-11-27 01:20 UTC, emilnormann commented on src/analysis/retail/priest/holy/modules/talents/BottomRow/DivineWord.tsx
> +const ACTIVATOR_SPELL_INCREASE = 0.3;
It is currently 30% on live.

2022-11-27 01:24 UTC, emilnormann commented
> I think I'm still not onboard with surfacing overhealing so prominently - I don't get the purpose of that for a heal like this.

I feel like showing overheal does not make it harder to read and is very useful for some talents imo. And by default I would show it for all talents for consistency. For this talent specifically it also shows very well if you made good use of the sanctify healing.

2022-11-27 01:56 UTC, kfinch approved these changes

2022-11-27 01:56 UTC, merged