remove uses of deprecated SL Combatant functions
WoWAnalyzer/WoWAnalyzer pull request #5461
Opened 2022-12-04 05:12 UTC by ToppleTheNun

convert uses of has2Piece to has2PieceByTier

convert uses of has4Piece to has4PieceByTier

replace ConduitLink with SpellLink

replace ConduitSpellText with BoringSpellValueText

replace all usages of Combatant#hasCovenant with false, then simplify

replace all usages of Combatant#hasSoulbind with false, then simplify

replace all usages of Combatant#hasConduit with false, then simplify

replace all usages of Combatant#hasCovenant with false, then simplify

replace all usages of Combatant#conduitRankBySpellID with 0, then simplify

2022-12-04 05:41 UTC, Sharrq commented
Im ok with the changes to the mage specs. I have been working through the specs and removing those references, but have not quite made it through all of them yet.

2022-12-04 05:44 UTC, Sharrq approved these changes
I approve the mage spec changes

2022-12-04 10:45 UTC, oisinod commented
@ToppleTheNun Priest stuff LGTM 👍

2022-12-04 15:08 UTC, vohrr requested changes
Couple of Mistweaver Suggestions

2022-12-04 15:08 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/features/Buffs.tsx
> +        enabled: false,
`enabled: combatant.hasTalent(TALENTS_MONK.BONEDUST_BREW_TALENT),`

2022-12-04 15:08 UTC, vohrr commented on src/analysis/retail/monk/shared/TouchOfDeath.js
> +      cooldown: 180,
`cooldown: 180 - 45 * this.selectedCombatant.getTalentRank(TALENTS_MONK.FATAL_TOUCH_TALENT.id),`

2022-12-05 08:18 UTC, trevorm4 commented
Monk looks good after the changes

2022-12-05 22:30 UTC, emallson approved these changes
I could've sworn i had updated those brew talents, but apparently i moved them and forgot to actually complete the updates 🤔

2022-12-05 22:55 UTC, darthelit commented
Fury warrior and rogue looking good to me

2022-12-07 18:55 UTC, Khazakdk approved these changes
Changes to DK modules look good

2022-12-07 18:58 UTC, merged