Disc guide damage section revamp
WoWAnalyzer/WoWAnalyzer pull request #5499
Opened 2022-12-11 18:04 UTC by oisinod

to be reviewed after #5498 

This one got a bit out of hand, I added a rotation analyser to damage, reordered the sections, and added some logic for the tooltips

2022-12-19 18:21 UTC, emallson requested changes

2022-12-19 18:21 UTC, emallson commented on src/analysis/retail/priest/discipline/modules/guide/RaptureAnalysis.tsx
> +          expanded={!isExpanded}
change the default value for `isExpanded` rather than inverting the logic here
```suggestion
          expanded={isExpanded}
```

2022-12-19 18:21 UTC, emallson commented on src/analysis/retail/priest/discipline/modules/guide/EvangelismAnalysis.tsx
> +          expanded={!isExpanded}
```suggestion
          expanded={isExpanded}
```
change the default value for `isExpanded` rather than inverting the logic here to avoid confusion later

2022-12-19 18:21 UTC, emallson commented on src/analysis/retail/priest/discipline/modules/guide/RaptureAnalysis.tsx
> +        } ${TE_SPELLS().includes(cast.ability.guid) && goodTeCast(index) ? '' : '--warning'}`;
these seem duplicated from `EvangelismAnalysis`. When possible, pull duplicated components out into a shared file.

2022-12-19 18:21 UTC, emallson commented on src/analysis/retail/priest/discipline/modules/guide/RaptureAnalysis.tsx
> +      );
these seem duplicated from `EvangelismAnalysis`.

2022-12-19 18:22 UTC, emallson commented
Sorry for the super delayed review! Was really slammed last week with raid release

2023-03-02 18:21 UTC, emallson reviewed
saw this had new changes. quick re-review, looks like the `isExpanded` and duplicated code comments still apply

2023-04-26 20:00 UTC, oisinod commented
Going to close this and re open when I have more time. There's too much changed by blizzard that I would rather just pick pieces from this branch and put it on a new branch/PR

2023-04-26 20:00 UTC, closed without merging