convert to react-router v6
WoWAnalyzer/WoWAnalyzer pull request #5590
Opened 2022-12-30 02:29 UTC by ToppleTheNun

fully functioning conversion to use react-router
v6 instead of react-router v5.

see WoWAnalyzer/WoWAnalyzer#5404 for additional
comment/context.

2023-01-07 19:13 UTC, emallson requested changes
some minor changes. im going to do some manual testing before we merge this for my own sanity

2023-01-07 19:13 UTC, emallson commented on src/interface/actions/reportHistory.ts
> +export interface ReportHistory {
```suggestion
export interface ReportHistoryEntry {
```

2023-01-07 19:13 UTC, emallson commented on src/interface/actions/reportHistory.ts
> +export function appendReportHistory(report: ReportHistory) {
```suggestion
export function appendReportHistory(report: ReportHistoryEntry) {
```

minor type name change for clarity---this type is not the history, but an *entry* in the history.

2023-01-07 19:13 UTC, emallson commented on src/interface/reducers/reportHistory.ts
> +export default function reportHistory(state: ReportHistory[] = defaultState, action: AnyAction) {
will also need type renames here. seems like a "let langserver handle it"

2023-01-12 15:32 UTC, emallson approved these changes
time to sit back and watch the fireworks

2023-01-12 16:25 UTC, ToppleTheNun commented
I plan to merge this tomorrow morning assuming that no conflicts or major issue arise before then.

2023-01-13 15:42 UTC, merged