Refactor/castigation and reverse normalizer
WoWAnalyzer/WoWAnalyzer pull request #5659
Opened 2023-01-15 20:54 UTC by oisinod

### Description

Refactor for castigation to use new atonement code. closes #5658 

Also reversed the referencing event with the linked event, thanks @trevorm4 👍

2023-01-15 23:47 UTC, trevorm4 requested changes

2023-01-15 23:47 UTC, trevorm4 commented on src/analysis/retail/priest/discipline/modules/spells/Castigation.tsx
> +    console.log(event);
get rid of log

2023-01-15 23:47 UTC, trevorm4 commented on src/analysis/retail/priest/discipline/modules/spells/Castigation.tsx
> +  testHealing = 0;
Get rid of this, doesn't look like it's used.

2023-01-16 23:06 UTC, oisinod commented
Good spots @trevorm4 thanks! Updated

2023-01-17 00:54 UTC, merged