Refactor/harsh discipline
WoWAnalyzer/WoWAnalyzer pull request #5692
Opened 2023-01-22 13:00 UTC by oisinod

### Description
Harsh Discipline uses atonement normalizer and not event anymore
closes #5691

2023-01-22 20:06 UTC, trevorm4 requested changes

2023-01-22 20:06 UTC, trevorm4 commented on src/analysis/retail/priest/discipline/modules/spells/HarshDiscipline.tsx
> +    if (damageEvent.penanceBoltNumber + 1 <= this.expectedBolts) {
```suggestion
    if (damageEvent.penanceBoltNumber < this.expectedBolts) {
```

2023-01-22 20:06 UTC, trevorm4 commented on src/analysis/retail/priest/discipline/modules/spells/HarshDiscipline.tsx
> +  private testAtonement = 0;
```suggestion
```

2023-01-28 23:09 UTC, oisinod commented
@trevorm4 I've added another commit adressing the comments you had but since they were missing I added the data for this module to also work with shadow penance

Thanks!

2023-01-29 03:28 UTC, trevorm4 approved these changes

2023-01-29 03:28 UTC, merged