Arms Warrior Execute EventLinkNormalizer
WoWAnalyzer/WoWAnalyzer pull request #5696
Opened 2023-01-23 15:07 UTC by Toreole

### Description

Implement suggested normalizer to link execute cast events to the damage event on the main target for reliable improved execute rage refund calculation.

2023-01-24 02:47 UTC, trevorm4 requested changes

2023-01-24 02:47 UTC, trevorm4 commented on src/analysis/retail/warrior/arms/normalizers/ExecuteNormalizer.tsx
> +  //assuming it varies with haste and server lag at the time.
You can remove this comment and make the 500ms a constant at the top of the file

2023-01-24 02:47 UTC, trevorm4 commented
Also, add a changelog entry in order for me to be able to merge it

2023-01-26 22:42 UTC, Toreole commented
Comment removed, changelog entry added. ready to merge.
More Arms changes coming in the next few days.

2023-01-27 00:28 UTC, ToppleTheNun approved these changes

2023-01-27 00:29 UTC, merged