[Balance] T29 4P
WoWAnalyzer/WoWAnalyzer pull request #5701
Opened 2023-01-24 12:43 UTC by ap2355

### Description

Module for Touch the Cosmos (Balance Druid T29 4P)

### Motivation

New module

### Testing

- Test report URL: /report/z3BJ1DkRrqp6y4j8/30-Mythic+Sennarth,+The+Cold+Breath+-+Kill+(6:53)/Idraly/standard/statistics
- Screenshot(s): 
- 
![image](https://user-images.githubusercontent.com/116091849/214293983-cdff3b04-e6fd-41dc-9a02-0c69f5e441b7.png)
![image](https://user-images.githubusercontent.com/116091849/214294610-bce0e59a-d58d-4659-b4c1-dcffb4cfe93d.png)

2023-01-24 20:46 UTC, hartra344 commented
I think I would consder removing the damage component on this one since there's really no way to correctly measure the damage amp for starfall. I think the > here hand waves it a little too much and isn't really a great approximation on any fight other than terros.

2023-01-25 15:51 UTC, kfinch commented
I'd be fine with the damage increase number if Starfall could be included, but I presume overlapping Starfalls make this not doable?

2023-01-25 19:26 UTC, hartra344 commented
> I'd be fine with the damage increase number if Starfall could be included, but I presume overlapping Starfalls make this not doable?



> I'd be fine with the damage increase number if Starfall could be included, but I presume overlapping Starfalls make this not doable?

yeah I don't think this is feasible since it's assigned to starfall on cast rather than damage and there's no way to descern which starfall ticks has the damage amp.

2023-01-25 20:24 UTC, hartra344 commented on src/analysis/retail/druid/balance/modules/spells/TouchTheCosmos.tsx
> +      <Statistic
one more nit I realized looking at the 2P code, cant you add it to the items category?

2023-01-26 12:12 UTC, ap2355 commented
I "removed" all the damage part but left it commented in the file if we want to reconsider it in a near future. This module will disappear next patch anyway.

2023-01-26 19:56 UTC, hartra344 approved these changes

2023-01-27 16:46 UTC, emallson requested changes
rather than doing a lot of commenting out, just delete the old code. we can retrieve it from git's history (and if you have questions / aren't sure how to do this, you can always ping me in discord for help)

2023-01-27 18:00 UTC, merged