add celestial section to mw guide
WoWAnalyzer/WoWAnalyzer pull request #5795
Opened 2023-02-13 05:17 UTC by trevorm4

Adds section for celestial setup and usage, yulon one is a bit bare bones atm because I haven't played it too much this expansion

![image](https://user-images.githubusercontent.com/11250934/218376502-731f1ead-f422-4756-b947-280b1f789b3b.png)
![image](https://user-images.githubusercontent.com/11250934/218376542-ce3e734b-1839-4817-a468-052260406e00.png)

2023-02-14 06:17 UTC, trevorm4 commented on src/analysis/retail/monk/mistweaver/modules/spells/BaseCelestialAnalyzer.tsx
> +const ENVM_HASTE_FACTOR = 0.55; // this factor determines how harsh to be for ideal envm casts
Open to changing this to .5 to be more lenient

2023-02-14 18:12 UTC, vohrr requested changes
Based on your screenshots in the PR description there is an incorrect tally for enveloping breath (max per cast is 6) 
Probably cause by the duplicate event handler but double check to be sure

2023-02-14 18:12 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/BaseCelestialAnalyzer.tsx
> +      (2 - this.selectedCombatant.getTalentRank(TALENTS_MONK.GIFT_OF_THE_CELESTIALS_TALENT)); // equal to celestial duration
Assuming this is supposed to be either 12 or 25 for the respective durations, it should be 12000 * ( 2 * getTalentRank + getTalentRank)

2023-02-14 18:12 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/BaseCelestialAnalyzer.tsx
> +  totalEnvM: number; // total envb applications
Comments don't match variable names (envm and envb)

2023-02-14 18:12 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/BaseCelestialAnalyzer.tsx
> +    this.addEventListener(
Duplicate event listener

2023-02-14 18:12 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/BaseCelestialAnalyzer.tsx
> +    this.siApplyTime = event.timestamp;
Include your 
`if(!this.celestialActive) return;` 
for applySi and applyLessons here since you are already grabbing the precast uptime in your OnSummon event handler

2023-02-14 18:12 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/BaseCelestialAnalyzer.tsx
> +    if (cast.totmStacks < 2) {
TotM stacks needs to be conditionally included for only chiji, this makes no sense for yulon

2023-02-14 18:12 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/BaseCelestialAnalyzer.tsx
> +    return this.idealEnvmCastsUnhasted * (1 + avgHaste * ENVM_HASTE_FACTOR);
- Needs some reconsideration in this for yulon vs chiji & jade bond vs gift. 
I would expect more envs per celestial window from yulon than chiji. 
Unhasted:
    Gift -> 4 yulon vs 3 chiiji,
    JB -> ~8 yulon vs 5-6 chiji

- This needs to have consideration for invoker's, I believe the buff is being captured in the HasteTracker by the avgHaste but its absence will also lower the ENV_HASTE_FACTOR

2023-02-14 18:12 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/BaseCelestialAnalyzer.tsx
> +    let efPerf = QualitativePerformance.Good;
Same thing for pre-ef hots, unnecessary before Yulon

2023-02-14 18:12 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/BaseCelestialAnalyzer.tsx
> +    const recastPerf = cast.recastEf ? QualitativePerformance.Good : QualitativePerformance.Fail;
Needs to be conditional based of Gift of the Celestials vs Jade Bond
EDIT: Looks like it is in InvokeChiji but not InvokeYulon

2023-02-14 18:12 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/InvokeChiJi.tsx
> +    this.addEventListener(
Add listener for SCK for the same purpose as these other two

2023-02-14 18:12 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/InvokeYulon.tsx
> +    super(options, 4 /* idealEnvmCasts */);
See comment in BaseCelestialAnalyzer

2023-02-14 18:12 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/InvokeChiJi.tsx
> +    super(options, 5.5 /* idealEnvmCasts */);
See comment in BaseCelestialAnalyzer

2023-02-14 19:15 UTC, trevorm4 commented on src/analysis/retail/monk/mistweaver/modules/spells/BaseCelestialAnalyzer.tsx
> +      (2 - this.selectedCombatant.getTalentRank(TALENTS_MONK.GIFT_OF_THE_CELESTIALS_TALENT)); // equal to celestial duration
Currently, if you have gift then goodLessonDuration is `12000 * (2 -1) = 12000` and if you don't have gift (aka jade bond), then it is `12000 * (2-0)`, which I think is correct?

2023-02-14 19:31 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/BaseCelestialAnalyzer.tsx
> +      (2 - this.selectedCombatant.getTalentRank(TALENTS_MONK.GIFT_OF_THE_CELESTIALS_TALENT)); // equal to celestial duration
No, base yulon and chiji are 25s

2023-02-15 04:53 UTC, trevorm4 commented on src/analysis/retail/monk/mistweaver/modules/spells/BaseCelestialAnalyzer.tsx
> +    return this.idealEnvmCastsUnhasted * (1 + avgHaste * ENVM_HASTE_FACTOR);
Changed constructor to always take in gift value and multiply accordingly.

2023-02-15 04:54 UTC, trevorm4 commented
Updated with code review suggestions
![image](https://user-images.githubusercontent.com/11250934/218935025-938a9337-3507-4f0b-b256-25f1e0ea1c41.png)
![image](https://user-images.githubusercontent.com/11250934/218935092-5b2eb99f-34b5-45ee-8997-146ca6ad83fa.png)

2023-02-15 14:22 UTC, vohrr approved these changes
A few wording nits but looks good. Fantastic work putting this whole guide together!

2023-02-15 14:22 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/InvokeChiJi.tsx
> +            that you can instantly cast <SpellLink id={SPELLS.BLACKOUT_KICK} /> for 6 total{' '}
6 additional * or 8 total (Bok + 3 Totm Boks)

2023-02-15 14:22 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/BaseCelestialAnalyzer.tsx
> +          Sufficient # of <SpellLink id={TALENTS_MONK.ENVELOPING_MIST_TALENT} /> casts
Sufficient Enveloping Mists casts (remove # of)

2023-02-15 14:22 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/InvokeYulon.tsx
> +            entire duration of <SpellLink id={TALENTS_MONK.INVOKE_CHI_JI_THE_RED_CRANE_TALENT} />
TALENTS_MONK.INVOKE_YULON_THE_JADE_SERPENT_TALENT

2023-02-15 21:28 UTC, merged