Classic Warrior
WoWAnalyzer/WoWAnalyzer pull request #5805
Opened 2023-02-15 14:51 UTC by Ac1dBomb

### Description

Learning as I go,  stupid syntax errors.  Might finally be fixed

### Motivation

### Testing

- Test report URL: `/report/...`
- Screenshot(s):

2023-02-15 14:55 UTC, Ac1dBomb commented
Im stuck now,  Syntax should be right.  Its telling me something about redeclaring name part.  Let me know ill fix it up and get this right.  Sorry tried pull request bunch of different times wasnt sure if I could repull through sameone but I closed the others.

2023-02-15 20:34 UTC, jazminite requested changes

2023-02-15 20:34 UTC, jazminite commented on src/CONTRIBUTORS.ts
> +};
Remove this entry, you have it in twice

2023-02-15 20:34 UTC, jazminite commented on src/common/SPELLS/classic/warrior.ts
> +Battle_Shout: {
All object keys need to be in all CAPS to follow style format.
So this one would be changed to `BATTLE_SHOUT`.
name values use title case

2023-02-15 20:34 UTC, jazminite commented on src/common/SPELLS/classic/warrior.ts
> +    name: 'Battle Shout (Rank 9)',
Names should not have `(Rank #)`.

2023-02-15 20:34 UTC, jazminite commented on src/common/SPELLS/classic/warrior.ts
> +   },
Each spell with multiple ranks needs a `lowRanks` attribute with the lower rank ids in an array. For example:
```suggestion
    lowRanks: [2048, 25289, 11551, 11550, 11549, 6192, 5242, 6673],
   },
```

2023-02-20 03:21 UTC, jazminite commented on src/common/SPELLS/classic/warrior.ts
> +import { spellIndexableList } from './Spell';
```suggestion
import { spellIndexableList } from '../Spell';
```

2023-02-21 11:00 UTC, closed without merging