[Mistweaver] Non-renewing mist hot graph
WoWAnalyzer/WoWAnalyzer pull request #5818
Opened 2023-02-17 23:15 UTC by vohrr

Added non-renewing mist HoT graph statistic and to the cooldown sections of the guide
![image](https://user-images.githubusercontent.com/26779541/219814789-8935c5e0-f987-4976-80a3-db00b1dd9408.png)

2023-02-17 23:32 UTC, trevorm4 requested changes

2023-02-17 23:32 UTC, trevorm4 commented on src/parser/shared/modules/BuffCountGraph.tsx
> - * over the course of an encounter.
replace all mistake?

2023-02-17 23:32 UTC, trevorm4 commented on src/analysis/retail/monk/mistweaver/modules/features/HotCountGraph.tsx
> +  }
Use `// eslint-disable-next-line no-useless-constructor` instead

2023-02-17 23:35 UTC, vohrr commented on src/parser/shared/modules/BuffCountGraph.tsx
> - * over the course of an encounter.
You know it

2023-02-18 05:54 UTC, trevorm4 approved these changes

2023-02-18 06:04 UTC, merged