[OUTLAW] Guide APL Checker
WoWAnalyzer/WoWAnalyzer pull request #5864
Opened 2023-03-02 18:43 UTC by Zac-oihfdwrrtuinvbcp

### Description

This is a first pass at an APL checker for outlaw, seems to be working fine for most of the basic stuffs but I do have some interrogations regarding some conditions that I cannot comprehend and get working.

1 - Every 'optional' condition seems to break everything, very simple example:
![image](https://user-images.githubusercontent.com/109383107/222517914-9ff8ef02-31d1-4233-9043-e8fbb7f844c4.png)
This is returning true whenever snc buff is down, this seems to be working fine in this sample example:
![image](https://user-images.githubusercontent.com/109383107/222518137-86b90a7e-f119-4bad-9cfa-18101332dc21.png)
We can see the user have no snc between 11 and 17s and is prompted to reroll, now if I un comment the `optional(buffMissing(SPELLS.BURIED_TREASURE)),` condition, as I understood it it should prompt the player to roll when snc and bt buffs are down but also allow him to keep bt alone same as it is doing with snc, however:
![image](https://user-images.githubusercontent.com/109383107/222519674-271597d6-ebaa-4d94-8e34-b0045b055287.png)
Suddenly even with both buffs down the user casts are not flagged as mistakes.

2 - Second thing I cannot figure out is how to use the pandemic option with the 'buffMissing' condition:
Here is my very simple BTE condition 
![image](https://user-images.githubusercontent.com/109383107/222520418-fa76a8b3-79f1-470e-bb90-b636ab90d665.png)
I want the user to have to refresh bte if the debuff is down but also be allowed to refresh up to 4s before (to not drop the debuff), bte is not a skill with actual pandemic and its duration is variable since its a finisher
![image](https://user-images.githubusercontent.com/109383107/222520821-07d31696-9f7c-4979-850e-b9f2db9786fe.png)
Here the user cast bte with max cp at 2s, he will apply the debuff for 21s, however he is prompted to refresh it as soon as the spell cd is back up

I couldn't understand exactly how the `debuffMissing` function was working especially since it doesn't have a 'RefreshDebuff' in it which would make me think it wouldn't handle refreshes? I also couldn't figure out what the `buffDuration` calculation was really doing.

Thanks in advance for the help.

### Motivation

### Testing

- Test report URL: `[/report/...](https://www.warcraftlogs.com/reports/t27zV8NLgPvJq3Kk#fight=17&type=casts&source=18&start=2483411&end=2526210)`
- Screenshot(s):
![image](https://user-images.githubusercontent.com/109383107/222517211-215fe1e2-feb7-4169-bd4b-6583a3dce4b6.png)

2023-03-02 19:00 UTC, emallson commented
- The `optional` thing looks like a bug
- I don't think `debuffMissing` has support for variable duration debuffs but could look at adding that :thinking: not exactly sure how to tie that in for the general case, might be better to have it be a custom condition for rogue stuff. Feral druid and evoker also have variable duration DoTs afaik. will have to look at it

2023-03-02 19:32 UTC, Zac-oihfdwrrtuinvbcp commented
> * I don't think `debuffMissing` has support for variable duration debuffs but could look at adding that 🤔 not exactly sure how to tie that in for the general case, might be better to have it be a custom condition for rogue stuff. Feral druid and evoker also have variable duration DoTs afaik. will have to look at it

Shouldn't the function at least work without a pandemic option, with simply `debuffMissing(SPELLS.BETWEEN_THE_EYES),`, glancing at the function I would think it would since it seems to just be checking if the debuff was present with apply and removeDebuff events
![image](https://user-images.githubusercontent.com/109383107/222532925-3dbeaceb-438e-48ca-8042-41533b852253.png)

but I still have the same issue

2023-03-02 21:19 UTC, Zac-oihfdwrrtuinvbcp commented
I looked a bit more into it and correct me if I'm wrong but I think there is a mistake in the debuffMissing function, 
![image](https://user-images.githubusercontent.com/109383107/222555741-2f9788ea-9ccf-4ea3-a20b-22dba97f860c.png)
When the `encodedTargetString` get created it currently set the second part of the string as 1 if no target instance is found, after checking what the `encodeEventTargetString` was returning it appears that the default `instance` is set to 0 and not 1, 
![image](https://user-images.githubusercontent.com/109383107/222556183-40bf62f9-11ff-4054-9a93-da918ad9653e.png)

2023-03-02 21:28 UTC, emallson commented
That does look like a bug with it, yup

On Thu, Mar 2, 2023, 4:19 PM zac ***@***.***> wrote:

> I looked a bit more into it and correct me if I'm wrong but I think there
> is a mistake in the debuffMissing function,
> [image: image]
> <https://user-images.githubusercontent.com/109383107/222555741-2f9788ea-9ccf-4ea3-a20b-22dba97f860c.png>
> When the encodedTargetString get created it currently set the second part
> of the string as 1 if no target instance is found, after checking what the
> encodeEventTargetString was returning it appears that the default instance
> is set to 0 and not 1,
> [image: image]
> <https://user-images.githubusercontent.com/109383107/222556183-40bf62f9-11ff-4054-9a93-da918ad9653e.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/WoWAnalyzer/WoWAnalyzer/pull/5864#issuecomment-1452561358>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABFOTERQN5GN7DKKK252L7TW2EFHPANCNFSM6AAAAAAVNXWMKY>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-03-03 18:48 UTC, Zac-oihfdwrrtuinvbcp commented
After looking a bit more into it I think there is more issues with this function:

-  it doesn't have a `RefreshDebuff` case contrary to the `buffMissing` function which seems to be built the same way,
- the `timeRemaining` which is being sent to the `buffDuration` function seems to also be incorrect to me

![image](https://user-images.githubusercontent.com/109383107/222800558-d2e4bdc7-d368-4098-88aa-0d1a2d2af44f.png)

The `buffDuration` function also seems to have some issues? Unless I am not properly understanding its purpose the calculation seems off to me, I am unsure what the pandemicCap original intended way of use was, the only very few examples of it being used seemed to be unsure aswell (from the brewmaster apl):
![image](https://user-images.githubusercontent.com/109383107/222802021-6fafba58-843f-436e-90d9-225ebb471b64.png)

![image](https://user-images.githubusercontent.com/109383107/222800679-a6ee0874-e326-4910-aa6d-0b29861a67eb.png)

If issues there is they would also be present in the `BuffMissing` function altough this only impact a few modules (only hunters and brewmaster modules are using it)

2023-03-03 21:47 UTC, emallson commented
Okay, I'm going to work on this this weekend. The brew thing is probably a
typo because I was in a bit of a hurry doing the last round of rotation
updates but as a whole this is not a great state for such a core condition
to be in

On Fri, Mar 3, 2023, 1:48 PM zac ***@***.***> wrote:

> After looking a bit more into it I think there is more issues with this
> function:
>
>    - it doesn't have a RefreshDebuff case contrary to the buffMissing
>    function which seems to be built the same way,
>    - the timeRemaining which is being sent to the buffDuration function
>    seems to also be incorrect to me
>
> [image: image]
> <https://user-images.githubusercontent.com/109383107/222800558-d2e4bdc7-d368-4098-88aa-0d1a2d2af44f.png>
>
> The buffDuration function also seems to have some issues? Unless I am not
> properly understanding its purpose the calculation seems off to me, I am
> unsure what the pandemicCap original intended way of use was, the only very
> few examples of it being used seemed to be unsure aswell (from the
> brewmaster apl):
> [image: image]
> <https://user-images.githubusercontent.com/109383107/222802021-6fafba58-843f-436e-90d9-225ebb471b64.png>
>
> [image: image]
> <https://user-images.githubusercontent.com/109383107/222800679-a6ee0874-e326-4910-aa6d-0b29861a67eb.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/WoWAnalyzer/WoWAnalyzer/pull/5864#issuecomment-1453956585>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABFOTEQQFEDLLSHZXNE5VDLW2I4HVANCNFSM6AAAAAAVNXWMKY>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-03-04 23:35 UTC, emallson commented
@Zac-oihfdwrrtuinvbcp I went through this afternoon and fixed *several* bugs with the buffMissing/debuffMissing implementation. Only one of them impacted brewmaster (`buffDuration` was not calculating partial pandemic extensions at all, always full extensions), which is part of why they went uncaught.

To remedy that, there are tests for both conditions now that should help ensure they behave going forward.

2023-03-05 00:09 UTC, emallson commented
I also looked into the behavior of `optional`. It isn't technically a bug, but the interaction with `and` is pretty confusing.

tl;dr - `optional` functions by checking if the spell being cast matches the one for the rule. if so, it checks the condition. if not, it says "this condition is not met". when combined with `and`, this means that any branch containing optional makes the whole thing optional.

I have done a couple of things to make this less of a footgun:

1. renamed `optional` -> `optionalRule` to indicate that it is for the *whole rule*
2. added a dev-time warning to `and` that triggers if any of the nested conditions use `optionalRule`.

To get the behavior you describe, you'll want to combine `and` and `or` with `optionalRule` (`or` doesn't have the same infectious behavior with nested `optionalRule`---though it still isn't super clear behavior):

```ts
or(
  // allow rerolling if you're missing either SnC or BT, but don't require it
  optionalRule(
    or(
      buffMissing(SPELLS.SKULL_AND_CROSSBONES),
      buffMissing(SPELLS.BURIED_TREASURE),
    )
  ),
  // require rerolling if you're missing both SnC and BT
  and(
    buffMissing(SPELLS.SKULL_AND_CROSSBONES),
    buffMissing(SPELLS.BURIED_TREASURE),
  )
)
```

2023-03-05 11:11 UTC, Zac-oihfdwrrtuinvbcp commented
Thanks a lot for all of this, I thought I would have to do something like that for the `optional` conditions after looking a bit more into the `and` but my brain couldn't really figure it out, your explanations and examples will greatly help me though, thanks again

2023-03-05 13:41 UTC, Zac-oihfdwrrtuinvbcp commented
Should have updated most of it, some things are still a bit inaccurate but It should be a decent first pass, would really appreciate a sanity check on the `optionalRule` conditions logic just in case my brain failed me. I went over casts from the timeline and the flagged casts seemed to be mostly accurate.

2023-03-06 16:53 UTC, emallson requested changes
some minor changes then we should be good to merge

2023-03-06 16:53 UTC, emallson commented on src/analysis/retail/rogue/outlaw/modules/apl/buffsCount.tsx
> +            return state !== null ? state + 1 : 0;
small bug, this is going to count the first buff application as 0 buffs.

simpler way:

```suggestion
            return (state ?? 0) + 1;
```

2023-03-06 16:53 UTC, emallson commented on src/analysis/retail/rogue/outlaw/modules/apl/buffsCount.tsx
> +            return state !== null ? state - 1 : 0;
this one shouldn't need to change since you don't want to end up at -1 buffs.

2023-03-06 16:53 UTC, emallson commented on src/analysis/retail/rogue/outlaw/CONFIG.tsx
> +    'https://www.warcraftlogs.com/reports/PVf9yQjhGDzZaBmv#fight=18&type=damage-done&source=11',
this should be a link to a wowa report, not a WCL report.

you can take the bit starting at `/report` from your local when testing

2023-03-06 16:53 UTC, emallson commented on src/analysis/retail/rogue/outlaw/modules/apl/AplCheck.tsx
> +      ),
i *think* this should work because the `or` will prevent the infectious interaction of `optionalRule` with `and`? something to keep an eye on.

2023-03-06 16:53 UTC, emallson commented on src/analysis/retail/rogue/outlaw/modules/apl/AplCheck.tsx
> +        or(not(hasFinisherCondition()), optionalRule(hasFinisherCondition())),
probably also works, i think?

2023-03-06 16:53 UTC, emallson commented on src/analysis/retail/rogue/outlaw/modules/apl/AplCheck.tsx
> +      }),
this probably needs to have a custom condition written for variable duration buffs, but i don't think that is a blocker.

2023-03-06 19:04 UTC, emallson approved these changes

2023-03-06 19:17 UTC, Zac-oihfdwrrtuinvbcp commented
Just wanted to add a small disclaimer about spells/talents missing to not potentially mislead users.

2023-03-06 19:42 UTC, merged