[Outlaw] Core rotation section with finisher subsection
WoWAnalyzer/WoWAnalyzer pull request #5897
Opened 2023-03-12 10:56 UTC by Zac-oihfdwrrtuinvbcp

### Description

First subsection of the core rotation section that tracks finisher usage.

Getting this error since I added this new subsection, not exactly sure what causes this
![image](https://user-images.githubusercontent.com/109383107/224540004-7ddb4b73-a270-4631-8627-5accb7f387ee.png)
Also very rarely after making a change? (not exactly sure when it actually happens, haven't been able to reproduce the issue) the boxes weren't getting all rendered, not sure if that would be linked to this error

### Testing

**Without Greenskin wickers talent:** `https://www.warcraftlogs.com/reports/kGZzydbhQrpMDLvw#fight=3&type=damage-done&source=16`
![image](https://user-images.githubusercontent.com/109383107/224539740-2dc42575-3f0b-4c48-a6c5-63c3abe1e356.png)

**With Greenskin wickers talent:** `https://www.warcraftlogs.com/reports/ADQxzVR9NvLt8rc4#fight=13&type=damage-done&source=111`
![image](https://user-images.githubusercontent.com/109383107/224539666-163f8769-24d1-4e4f-b8aa-1e589dc1f580.png)

2023-03-12 23:07 UTC, emallson commented
the `:nth-child` error is just a warning for SSR, which we don't use. it can be safely ignored.

2023-03-18 20:32 UTC, Zac-oihfdwrrtuinvbcp commented
Hey @emallson. Sorry to bother, I was just wondering if you had a chance to take a look at this PR? No pressure, I understand if you didn't have the time. I just wanted to check in and make sure it didn't get lost or forgotten. Also, no rush on this, I don't have any other PRs coming up just yet anyway. Thanks

2023-03-18 20:40 UTC, emallson commented
i have an in-progress review that i forgot to finish. i'll wrap that up :)

2023-03-18 20:48 UTC, emallson requested changes

2023-03-18 20:48 UTC, emallson commented on src/analysis/retail/rogue/outlaw/modules/core/FinisherUse.tsx
> +    }
this should probably be split out into several methods. really big switch bodies are a source of pretty sneaky bugs related to missing `break`s

2023-03-18 20:49 UTC, emallson commented
I am not 100% sold on using the box grids for these kinds of very frequent spells. It works (and there is something nice about seeing a sea of green) but there may be better options.

but, we don't need perfection to put things online. it just needs to be good, which i think is the case here

2023-03-19 10:45 UTC, Zac-oihfdwrrtuinvbcp commented
> this should probably be split out into several methods. really big switch bodies are a source of pretty sneaky bugs related to missing `break`s

So I can do it like that, just splitting what's in each switch block into a method, it feels a bit silly tho, not sure exactly if that would be the correct approach, I especially don't like that I'm copy pasting some variables like `bteCDRemainingTime` and `bteDebuffRemainingTime` into the methods but I'm not sure if sending them as parameters would make much sense either

2023-03-19 18:02 UTC, emallson approved these changes
i think this is good, the main issue with large `switch` statements is accidentally falling through, so a big if/else is also a choice there. small switches are easier to work with and avoid the sneaky accidental fallthrough

2023-03-19 18:13 UTC, merged