Arcane Mage - Show percentage of good Touch Uses
WoWAnalyzer/WoWAnalyzer pull request #5933
Opened 2023-03-19 07:19 UTC by cameronstubber

### Description

fixes #5926 

Correctly formats the number as a percentage and shows good instead of bad value

### Motivation

To stop the GUI Bug showing lots of decimal places

### Testing

Raw values in the provided log were 1 bad out of 7 total casts or 14% Bad, 86% Good.

/report/GNdWwV8Fj1qKfrCJ/14-Mythic+Terros+-+Kill+(4:41)/Zaleaqt/standard/about

Before:
![image](https://user-images.githubusercontent.com/18435180/226160104-df51aeb2-99cf-42cf-93e5-100ef40bd7f8.png)

After:
![image](https://user-images.githubusercontent.com/18435180/226160070-a0cea7cc-d365-412f-b261-0b4c784ea316.png)

2023-03-23 05:25 UTC, trevorm4 requested changes

2023-03-23 05:25 UTC, trevorm4 commented on src/analysis/retail/mage/arcane/talents/ArcaneEcho.tsx
> +            {formatNumber(this.touchUtilization * 100)}%{' '}
Use `formatPercentage` instead

2023-03-24 06:01 UTC, cameronstubber commented on src/analysis/retail/mage/arcane/talents/ArcaneEcho.tsx
> +            {formatNumber(this.touchUtilization * 100)}%{' '}
Yep, thats fair.

2023-03-30 05:12 UTC, trevorm4 approved these changes

2023-03-30 05:31 UTC, merged