tier 30 support for holy priest
WoWAnalyzer/WoWAnalyzer pull request #6008
Opened 2023-04-23 21:11 UTC by foobartles

### Description

Add support for the Tier 30 4 set for holy priest. I don't think it is possible to track 2 piece because of the way that PoM is logged to the combat log. It would not be clear if a PoM application is tied to 2 piece proc or is just from an existing PoM bouncing.

### Testing
Test report from PTR:
https://www.warcraftlogs.com/reports/AkdM1wpqKVTrLYFG#fight=17
<img width="377" alt="image" src="https://user-images.githubusercontent.com/6947753/233866494-3e765b37-c80a-41d1-80e5-5324e28929a1.png">

2023-04-23 23:41 UTC, trevorm4 commented
It's possible to track the 2 piece but it would require a decent amount of coding, you would need to do event linking and apply similar logic to Dancing Mists to track which are from casts and which are from procs (similar idea to dancing mist tracking)

2023-04-23 23:44 UTC, trevorm4 requested changes

2023-04-23 23:44 UTC, trevorm4 commented on src/analysis/retail/priest/holy/modules/dragonflight/tier/tier30/Tier30HolyPriest4Set.tsx
> +    console.log(stacks);
Get rid of this log

2023-04-23 23:44 UTC, trevorm4 commented on src/analysis/retail/priest/holy/modules/dragonflight/tier/tier30/Tier30HolyPriest4Set.tsx
> +      console.log(healEvents);
Remove

2023-04-23 23:44 UTC, trevorm4 commented on src/common/SPELLS/priest.ts
> +  },
Put this in ITEMS/priest.ts instead

2023-04-25 00:08 UTC, foobartles commented
> It's possible to track the 2 piece but it would require a decent amount of coding, you would need to do event linking and apply similar logic to Dancing Mists to track which are from casts and which are from procs (similar idea to dancing mist tracking) since procs will generally apply after the original bounce.

I can look into doing this if I have time, haven't really been playing my priest recently so my motivation for stuff like that has gone down the drain haha

2023-04-25 06:30 UTC, trevorm4 commented
I saw you requested review but don't see a new commit, did you forget to push?

2023-04-25 14:56 UTC, foobartles commented
> I saw you requested review but don't see a new commit, did you forget to push?

🤦 My bad, I hit push but closed my laptop before it finished and the push timed out lol. Sorry about that, should be pushed now

2023-04-25 23:41 UTC, trevorm4 approved these changes

2023-04-25 23:53 UTC, merged