Evoker guide pt 2
WoWAnalyzer/WoWAnalyzer pull request #6047
Opened 2023-05-07 05:41 UTC by trevorm4

### Description

Adds sections for EC, Stasis, Essence Burst

### Testing

- Test report URL: `/report/...`
- Screenshot(s):
![image](https://user-images.githubusercontent.com/11250934/236659399-1bef1b45-5fc9-4339-9045-e614d3791c3a.png)
![image](https://user-images.githubusercontent.com/11250934/236659464-3e3914fb-4daa-4c54-bb67-b1bc0cba425c.png)

2023-05-08 03:03 UTC, vohrr requested changes
Mostly good, some grammar stuff, copy/paste remnants and a few suggestions

2023-05-08 03:03 UTC, vohrr commented on src/analysis/retail/evoker/preservation/modules/talents/EmeraldCommunion.tsx
> +                  seconds of channeling{' '}
Capitalize Seconds

2023-05-08 03:03 UTC, vohrr commented on src/analysis/retail/evoker/preservation/modules/talents/EmeraldCommunion.tsx
> +              result: <PerformanceMark perf={targetsHitPerf} />,
Similar comment to the dreamflight subsection, do `15/20 targets with lifebind` etc

2023-05-08 03:03 UTC, vohrr commented on src/analysis/retail/evoker/preservation/modules/talents/EmeraldCommunion.tsx
> +            const secondsChanneling = Math.max(0, (info.endChannelTime - info.timestamp) / 1000);
precision

2023-05-08 03:03 UTC, vohrr commented on src/analysis/retail/evoker/preservation/modules/talents/EssenceBurst.tsx
> +      if (info.spell === 0 || badEb || badDisintegrate) {
We should have a badEcho const defined here for when an EB build is being run, yes?

2023-05-08 03:03 UTC, vohrr commented on src/analysis/retail/evoker/preservation/modules/talents/Ouroboros.tsx
> +  subStatistic() {
delete?

2023-05-08 03:03 UTC, vohrr commented on src/analysis/retail/evoker/preservation/modules/talents/Stasis.tsx
> +  getAnalysisForSpell(spell: number, forRamp: boolean) {
I really like the descriptions but its very wordy for a checklist. Could the bulk of these be tossed into a tooltip (similar to how we do for MW) and only display a spell link for the stored spell? 
Example: 
![image](https://user-images.githubusercontent.com/26779541/236723665-4ec6755f-4562-4ab1-9468-e93e9b4da2aa.png)

2023-05-08 03:03 UTC, vohrr commented on src/analysis/retail/evoker/preservation/modules/talents/Stasis.tsx
> +            <SpellLink spell={SPELLS.EMERALD_BLOSSOM} /> when doing a{' '}
an* Emerald Communion

2023-05-08 03:03 UTC, vohrr commented on src/analysis/retail/evoker/preservation/modules/talents/Stasis.tsx
> +            <SpellLink spell={TALENTS_EVOKER.STASIS_TALENT} /> is used for a{' '}
an*

2023-05-08 03:03 UTC, vohrr commented on src/analysis/retail/evoker/preservation/modules/talents/Stasis.tsx
> +            not a high value spell to store when not doing a{' '}
an*

2023-05-08 03:03 UTC, vohrr commented on src/analysis/retail/evoker/preservation/modules/talents/Stasis.tsx
> +            store when not doing a <SpellLink spell={TALENTS_EVOKER.EMERALD_COMMUNION_TALENT} />{' '}
an*

2023-05-08 03:03 UTC, vohrr commented on src/analysis/retail/evoker/preservation/modules/talents/Stasis.tsx
> +            store when not doing a <SpellLink spell={TALENTS_EVOKER.EMERALD_COMMUNION_TALENT} />{' '}
an

2023-05-08 03:03 UTC, vohrr commented on src/analysis/retail/evoker/preservation/modules/talents/Stasis.tsx
> +        identical targets. Noteably, it can not store{' '}
Notably*

2023-05-08 03:03 UTC, vohrr commented on src/analysis/retail/evoker/preservation/normalizers/CastLinkNormalizer.ts
> +  },
Might want to add an additionalCondition(c) here for .hasTalents for Reso Sphere/Lifebind/whatever else here just in case

2023-05-08 04:20 UTC, trevorm4 commented
Code review updates
![image](https://user-images.githubusercontent.com/11250934/236732983-8828b187-0ed8-40ab-8376-a9d2f69c25ff.png)

2023-05-09 02:52 UTC, vohrr approved these changes

2023-05-09 05:24 UTC, merged