Adds FlameShock guide section.
WoWAnalyzer/WoWAnalyzer pull request #6215
Opened 2023-07-16 00:13 UTC by periodic

### Description

Adds a section to the Elemental Shaman guide for Flame Shock.  It shows the total uptime, stack history graph and number of Lava Bolts that needed Flame Shock.

The guide is still a prototype.  This is just filling in one section.

### Testing

- Test report URL: `/report/6tVWMyQP4cb1kmBa/10-Heroic+The+Forgotten+Experiments+-+Kill+(3:58)/Ironshock/standard#prototype`
- Screenshot(s):

Before:
<img width="983" alt="image" src="https://github.com/WoWAnalyzer/WoWAnalyzer/assets/321389/cca03242-dc83-4582-b095-f8440cdf716e">

After:
<img width="981" alt="image" src="https://github.com/WoWAnalyzer/WoWAnalyzer/assets/321389/36fa391f-6e10-467f-a625-131704b89bb8">

2023-07-16 00:13 UTC, periodic commented
cc: @awildfivreld

2023-07-16 18:09 UTC, awildfivreld commented
When you hover over an uptime section, does it show from-to time? I've found that nice to correlate with other things/the timeline.

2023-07-17 17:05 UTC, emallson requested changes
minor change, but this looks reasonable overall

2023-07-17 17:05 UTC, emallson commented on src/parser/shared/modules/Enemies.ts
> +          console.log('Adding entry', prevTimestamp, event.timestamp, prevActive);
stray `console.log`

2023-07-27 03:25 UTC, periodic commented on src/parser/shared/modules/Enemies.ts
> +          console.log('Adding entry', prevTimestamp, event.timestamp, prevActive);
Ah, thanks.  Missed that one.

2023-07-27 17:43 UTC, emallson approved these changes

2023-07-27 17:56 UTC, merged