Add ancient flame module to Preservation Evoker guide
WoWAnalyzer/WoWAnalyzer pull request #6251
Opened 2023-07-24 04:16 UTC by trevorm4

### Description

Adds module/guide section for ancient flame when spec'd into eb talents since its very useful for dps and generating eb procs

### Testing

- Test report URL: `report/f2MTV1hH3zZjWk47/28-Mythic+Rashok,+the+Elder+-+Kill+(5:47)/Widdeldwagon/standard/overview`
- Screenshot(s):

![image](https://github.com/WoWAnalyzer/WoWAnalyzer/assets/11250934/d87f18a2-1e5a-4c2d-9748-2e5faf1375b7)
![image](https://github.com/WoWAnalyzer/WoWAnalyzer/assets/11250934/9c92d0f5-9423-4563-993e-bbe1d4773d50)
![image](https://github.com/WoWAnalyzer/WoWAnalyzer/assets/11250934/5ff5a503-9aac-45d8-b8d5-23ec2fef948d)

2023-07-24 14:24 UTC, vohrr requested changes

2023-07-24 14:24 UTC, vohrr commented on src/analysis/retail/evoker/preservation/modules/features/Abilities.tsx
> +          base: 500,
Does Fire Breath need to be added & included here

2023-07-24 14:24 UTC, vohrr commented on src/analysis/retail/evoker/preservation/modules/talents/AncientFlame.tsx
> +    if (this.selectedCombatant.getBuffStacks(SPELLS.ESSENCE_BURST_BUFF.id) === 1) {
Probably need to track last proccing cast, this misses the refresh event triggered by verdant embrace w/1 EB stack which would be a bad cast. 

1 Stack Essence Burst & Ancient Flame Active  -> VE Cast -> Bad Refresh

Or at the very least the tooltip would be inaccurate for this scenario

2023-07-24 14:24 UTC, vohrr commented on src/analysis/retail/evoker/preservation/modules/talents/AncientFlame.tsx
> +        <SpellLink spell={TALENTS_EVOKER.ESSENCE_BURST_PRESERVATION_TALENT} />. Not utilizing this
"Not utilizing this talent will reduce your HPS, DPS, and Mana efficiency"

2023-07-24 14:24 UTC, vohrr commented on src/analysis/retail/evoker/preservation/modules/talents/AncientFlame.tsx
> +        than it should be. It is okay to cast multiple <SpellLink spell={SPELLS.EMERALD_BLOSSOM} />s
Specify when it is ok (cast at max stacks/high dmg etc.)

2023-07-25 01:32 UTC, trevorm4 commented on src/analysis/retail/evoker/preservation/modules/features/Abilities.tsx
> +          base: 500,
Fire Breath is in the shared abilities module

2023-07-25 02:36 UTC, trevorm4 commented
Addressed comments

2023-07-25 17:05 UTC, vohrr approved these changes

2023-07-26 00:33 UTC, merged