Updates to the support for sepsis in assassination
WoWAnalyzer/WoWAnalyzer pull request #6331
Opened 2023-08-24 06:28 UTC by juemrami

### Description
Finished implementation initially started by Whispyr.

Includes:
 - Sepsis Normalizer module
 - New assassination rogue specific Sepsis spell cooldown module 
 - Improved clarity on snapshot module for tracking garrotes improved through sepsis buffs.
 - Thistle Tea logic for catching split-second casts overcapping very small amounts of energy 

- Screenshot(s):
![sepsis-snapshot-example](https://i.imgur.com/wk2Z0oP.png )
![spesis-cooldown-example](https://i.imgur.com/buJplOQ.png)

2023-08-27 18:01 UTC, ToppleTheNun requested changes
The only things that _need_ to be fixed to get this in are below, otherwise I have a few suggestions:
- remove the stray `console.debug`
- remove the lingui wrapper in Sepsis.tsx

2023-08-27 18:01 UTC, ToppleTheNun commented on src/analysis/retail/rogue/assassination/CHANGELOG.tsx
> +  change(date(2023, 8, 24), `Improved support for Sepsis with Coooldown breakdown + Snapshoting`, Bigsxy),
You could dual-attribute this change and remove the change further down:
```suggestion
  change(date(2023, 8, 24), `Improved support for Sepsis with Coooldown breakdown + Snapshoting`, [Bigsxy, Whispyr]),
```

2023-08-27 18:01 UTC, ToppleTheNun commented on src/analysis/retail/rogue/assassination/modules/spells/GarroteUptimeAndSnapshots.tsx
> +      console.debug(snapshots, prevSnapshots);
stray `console.debug`

2023-08-27 18:01 UTC, ToppleTheNun commented on src/analysis/retail/rogue/assassination/normalizers/SepsisLinkNormalizer.ts
> +    isActive: isUsingSepsis,
Should be able to drop these `isActive` if you set the analyzer module to be active/inactive using the same method.

2023-08-27 18:01 UTC, ToppleTheNun commented on src/analysis/retail/rogue/assassination/normalizers/SepsisLinkNormalizer.ts
> +    super(options, EVENT_LINKS);
If you add `this.active = this.selectedCombatant.hasTalent(TALENTS.SEPSIS_TALENT)` in the constructor, you should be able to drop the `isActive` in the links themselves.

2023-08-27 18:01 UTC, ToppleTheNun commented on src/analysis/retail/rogue/assassination/modules/talents/Sepsis.tsx
> +            <Trans id="guide.rogue.assassination.sections.cooldowns.sepsis.explanation">
I suggest not using the lingui components here, as we're making an effort to reduce the i18n in the spec modules. You can just remove the `<Trans id="guide.rogue.assassination.sections.cooldowns.sepsis.explanation">` wrapper and it should be fine.

2023-08-27 18:01 UTC, ToppleTheNun commented on src/analysis/retail/rogue/assassination/modules/talents/Sepsis.tsx
> +          Consume the first <SpellLink spell={SPELLS.SEPSIS_BUFF} /> buff with{' '}
This is a bit lengthy for a summary; it's a bit hard to simplify it, but maybe something like:
```tsx
<>
  First buff consumed by <SpellLink spell={SPELLS.GARROTE} />
</>
```

2023-08-27 18:01 UTC, ToppleTheNun commented on src/analysis/retail/rogue/assassination/modules/talents/Sepsis.tsx
> +          Consume the second <SpellLink spell={SPELLS.SEPSIS_BUFF} /> buff with{' '}
This is also a bit lengthy. In a similar vein to the previous, maybe:
```tsx
<>
  Second buff consumed by <SpellLink spell={SPELLS.GARROTE} />
</>
```

2023-08-27 18:01 UTC, ToppleTheNun commented on src/analysis/retail/rogue/assassination/modules/talents/Sepsis.tsx
> +            {formatSeconds(buff.timeRemainingOnRemoval, 2)} seconds remaining it's duration.
`remaining on its duration`

2023-08-27 18:01 UTC, ToppleTheNun commented on src/analysis/retail/rogue/assassination/modules/talents/Sepsis.tsx
> +            buffPerformance = QualitativePerformance.Good;
Is this a `Good` performance if the usage details slightly further down says `This is okay`?

2023-08-27 18:01 UTC, ToppleTheNun commented on src/analysis/retail/rogue/assassination/modules/talents/Sepsis.tsx
> +    const shivSummary: React.ReactNode = (
This summary is also a bit long; maybe the below and shift the remainder into the details view:
```tsx
<div>
  Cast a full-length <SpellLink spell={SPELLS.SHIV} /> 
</div>
```

2023-08-27 18:01 UTC, ToppleTheNun commented on src/analysis/retail/rogue/assassination/modules/talents/Sepsis.tsx
> +    [initialBuffApplication, delayedBuffApplication, debuffApplication].forEach((application) => {
I'd suggest making this a bit simpler by doing:
```tsx
[initialBuffApplication, delayedBuffApplication, debuffApplication].filter(isDefined).forEach((application) =>
```

Then you can remove one layer of nesting and make this easier to read.

2023-08-28 02:23 UTC, juemrami commented on src/analysis/retail/rogue/assassination/modules/spells/GarroteUptimeAndSnapshots.tsx
> +      console.debug(snapshots, prevSnapshots);
oh man, embarrassing xD

2023-08-28 04:16 UTC, juemrami commented on src/analysis/retail/rogue/assassination/CHANGELOG.tsx
> +  change(date(2023, 8, 24), `Improved support for Sepsis with Coooldown breakdown + Snapshoting`, Bigsxy),
Got it, the earlier entry was there from when i branched @Whispyrs WIP, i wasnt sure if i should have kept it in or not.

2023-08-30 06:23 UTC, juemrami commented
> The only things that _need_ to be fixed to get this in are below, otherwise I have a few suggestions:
> 
>     * remove the stray `console.debug`
> 
>     * remove the lingui wrapper in Sepsis.tsx

addressed in https://github.com/WoWAnalyzer/WoWAnalyzer/pull/6331/commits/f45ca849b73842f44cf0f4824cf46d17b01a667a and https://github.com/WoWAnalyzer/WoWAnalyzer/pull/6331/commits/233bb8637a96c406a084040d55d7041c9df4d608 respectively.

2023-09-02 16:41 UTC, ToppleTheNun approved these changes

2023-09-02 16:52 UTC, merged