[FROST DK] KM out-of-gcd Fix
WoWAnalyzer/WoWAnalyzer pull request #6547
Opened 2023-12-03 16:25 UTC by Bicepspump

### Description

The code currently counts Killing Machine generations that are out-of-GCD, categorising them as minor mistakes due to the player not being able to prevent them. However, this is also currently catching manually generated KM procs that do not occur outside the GCD. The reason for this is that the KM buff event occurs just after the actual GCD (0 or 1 MS) and is therefore caught as inside a GCD.

### Testing

- Test report URL: https://www.warcraftlogs.com/reports/ZqFVTL8Q9AwBgf7M#fight=17&type=damage-done&source=430
- Screenshot(s):
New -> ![image](https://github.com/WoWAnalyzer/WoWAnalyzer/assets/34515306/3951de7b-1526-482f-b0cf-973488b8aa06)
Old -> ![image](https://github.com/WoWAnalyzer/WoWAnalyzer/assets/34515306/503d9344-9bf4-401b-add3-bfd1aa0e3a07)

2023-12-03 16:45 UTC, Khazakdk requested changes
You’ve changed the behavior of the module without updating the UI to clearly communicate what’s going on.  In addition, like I said on Discord, you need to use something more like an apl module for tracking manual km generation.  Red errors are for undisputed mistakes.  There are times when manual km generation may lead to proc wastes due to resource constraints.

2023-12-03 18:01 UTC, Bicepspump commented
> You’ve changed the behavior of the module without updating the UI to clearly communicate what’s going on. In addition, like I said on Discord, you need to use something more like an apl module for tracking manual km generation. Red errors are for undisputed mistakes. There are times when manual km generation may lead to proc wastes due to resource constraints.

The current UI clearly states that the red KMs should be "Killing Machines refreshed during an available GCD" which the functionality doesn't do. If you are in your pillar and generate a KM manually on an available GCD, it counts it as being in a GCD and adds it to the yellow bar.

My change is simply to fix this incorrect behavior, not change the functionality.

2023-12-03 19:25 UTC, Khazakdk commented
The wording is accurate.  It might need additional explanation when oblit is talented but remember the module needs to work for all builds.  Again, what really needs to be done is a specific module for obliteration that considers the current state of the player

2023-12-03 19:26 UTC, Khazakdk commented
We only flag things to the red bar when it’s caused by a player mistake.  KMs refreshed inside pillar are not necessarily player mistakes.

2024-01-05 16:15 UTC, ToppleTheNun commented
With feedback given and not addressed for a month, I'm closing the PR.

If the comments are resolved, feel free to reopen this PR.

2024-01-05 16:15 UTC, closed without merging