Fix/winters chill 4 icicles
WoWAnalyzer/WoWAnalyzer pull request #6674
Opened 2024-03-14 11:42 UTC by earosselot

### Description

Fix a bug where a flurry cast without precast was marked as fail when casted at 4 icicles (altough is a correct cast). 

Flurry event at 4 icicles before:
![image](https://github.com/WoWAnalyzer/WoWAnalyzer/assets/32552126/03950641-6933-4eaa-90ba-60fa261806ad)

Flurry event at 4 icicles now:
![image](https://github.com/WoWAnalyzer/WoWAnalyzer/assets/32552126/cf3dda2f-ae6c-4c2f-8aa4-a82eccd87ff4)

[Link to log](https://www.warcraftlogs.com/reports/gLfHRVjd7ByKkxqF#fight=last&type=casts&source=2&view=events&pins=2%24Off%24%23244F4B%24expression%24ability.name%20in%20(%22Glacial%20Spike%22,%20%22Ice%20Lance%22,%20%22Flurry%22)%5E0%24Separate%24%23909049%24auras-gained%24-1%24183490188.0.0.Mage%24183490188.0.0.Mage%24true%24183490188.0.0.Mage%24true%24205473)

[Link to video](https://www.youtube.com/watch?v=qsXpG2Oe5TM&ab_channel=EduardoRosselot) showing the flurry cast on 4 icicles at @0:16

The problem was caused by the method getBuffStacks returning the last stack update of the active buff and not the stacks at the requested timestamp. I made a correction thath might not be the JS way to do it :).

For example: 
![image](https://github.com/WoWAnalyzer/WoWAnalyzer/assets/32552126/76bc7e26-5212-4e06-8005-083911a9966a)
For this buff object you will always get 5 stacks if all the stacks were processed, even if you ask for the 13seconds timestamp.

2024-03-14 17:47 UTC, emallson commented on src/parser/core/Entity.ts
> +    return stacks;
what edge case does this address beyond just calling `getBuff` with the `forTimestamp` value? is `buff.stacks` always the last-seen value of stacks, not necessarily the one at `forTimestamp`?

2024-03-14 20:45 UTC, earosselot commented on src/parser/core/Entity.ts
> +    return stacks;
> what edge case does this address beyond just calling `getBuff `with the `forTimestamp `value?

This method looks into the stackHistory array and gathers the lastest update for the given timestamp.

> is `buff.stacks` always the last-seen value of stacks, not necessarily the one at `forTimestamp`?

As far as I know, yes. I show you this debug case to make my point:
![image](https://github.com/WoWAnalyzer/WoWAnalyzer/assets/32552126/098bdaf4-7e90-45f4-ba2c-e33bdacb6f83)

As you can see, the calls to `getBuff` are both returning 5 stack when they (as I understand the intended behavior of the method) should return 4 and 2 for `forTimestamp` and `forTimestamp-2000` respectively.

the code now does return these values (same debug position as above):
![image](https://github.com/WoWAnalyzer/WoWAnalyzer/assets/32552126/2bb601e2-9fc6-45c2-8af3-607f14baeb42)

I don't know if I'm explaining good enough. Also, I think this should be tested in some clases to watch the behavior of the change.

2024-03-14 21:17 UTC, emallson commented on src/parser/core/Entity.ts
> +    return stacks;
that makes sense :+1:

2024-03-17 18:43 UTC, emallson requested changes

2024-03-17 18:43 UTC, emallson commented on src/parser/core/Entity.ts
> +      if (maxStackForTimestamp.stacks < stack.timestamp && stack.timestamp < currentTimestamp) {
looks like a typo here. this should be:

```suggestion
      if (maxStackForTimestamp.timestamp < stack.timestamp && stack.timestamp < currentTimestamp) {
```

2024-03-17 23:50 UTC, earosselot commented on src/parser/core/Entity.ts
> +      if (maxStackForTimestamp.stacks < stack.timestamp && stack.timestamp < currentTimestamp) {
ups

2024-03-17 23:50 UTC, earosselot commented on src/parser/core/Entity.ts
> +    return stacks;
I've checked on some clases that use the method and everything looks the same.

2024-03-18 05:20 UTC, merged