[Discipline] Add Amirdrassil 4p Smite to places & Misc Fixes
WoWAnalyzer/WoWAnalyzer pull request #6753
Opened 2024-05-03 07:04 UTC by Saeldur

### Description
- Fix a bunch of outdated ability cooldowns/categorisations
- Remove some outdated spells from showing in the list
- Add Amirdrassil Shadow Smite to all smite talents
- Fix Ultimate Penance Cooldown (It was referring to the damage spell not the cast spell)
- Fix Heavens Wrath (Outdated implementation)

### Testing
- https://www.warcraftlogs.com/reports/Np7YBKTDxz9qCkn4#fight=3&type=summary&source=87 - Blaze / TE Fixes
- https://www.warcraftlogs.com/reports/xBQfWD2Mg8A1qdzh#fight=81&type=healing&source=13 - Ultimate Penitence Fixes

2024-05-03 07:43 UTC, Krealle commented
LGTM

2024-05-04 02:02 UTC, trevorm4 requested changes
small nits and then lgtm

2024-05-04 02:02 UTC, trevorm4 commented on src/analysis/retail/priest/discipline/modules/spells/BlazeOfLight/BlazeOfLight.tsx
> +        .spell([SPELLS.SMITE, SPELLS.SHADOW_SMITE, SPELLS.PENANCE, SPELLS.DARK_REPRIMAND_DAMAGE]),
```suggestion
        .spell(BLAZE_OF_LIGHT_SPELLS),
```

2024-05-04 02:02 UTC, trevorm4 commented on src/analysis/retail/priest/discipline/modules/spells/TwilightEquilibrium/TwilightEquilibrium.tsx
> +      return false;
```suggestion
      return this.selectedCombatant.hasBuff(SPELLS.TWILIGHT_EQUILIBRIUM_HOLY_BUFF.id, event.timestamp);
```

2024-05-04 02:02 UTC, trevorm4 requested changes
small nits and then lgtm

2024-05-08 01:29 UTC, emallson commented
looks like everything is addressed, gonna merge shortly

2024-05-08 01:36 UTC, merged