rough draft of the foundation guide, using Cata BDK as a guinea pig
WoWAnalyzer/WoWAnalyzer pull request #6832
Opened 2024-06-19 21:52 UTC by emallson

this adds a basic *Foundation Guide* that uses core analyzers to produce some basic analysis with minimal additional code.

the goal is for you to be able to take this and plug it in to a previously-unsupported spec to get something useful just by setting up the core analyzers.

i ended up punting on the resource section for now because we don't have any truly core (in the sense that they operate off of the Config or Abilities) pieces for that just yet. However, I think that having a shorthand to set up `ResourceTracker` / `ResourceGraph` will be a good solution.

(the `App.scss` changes are mostly whitespace. i dropped the line height a little because we're doing more prose)

![image](https://github.com/WoWAnalyzer/WoWAnalyzer/assets/4909458/2441aefd-6845-4f04-99b5-d006854a484d)

### Misc Other Changes

- Added a warning about food/flask logging in Cata Classic
- Small tweak to the `Highlight` component

2024-06-19 22:43 UTC, jazminite requested changes
Wording suggestions :)

2024-06-19 22:43 UTC, jazminite commented on src/interface/guide/foundation/FoundationCooldownSection.tsx
> +          Perfect cooldown usage is a kind of art&mdash;a combination of in-depth fight knowledge
```suggestion
          Perfect cooldown usage is a combination of in-depth fight knowledge
```

2024-06-19 22:43 UTC, jazminite commented on src/interface/guide/foundation/FoundationCooldownSection.tsx
> +          and player skill to get exceptional output. However, 90% of the time you can get 90% of
```suggestion
          and player skill. However, 90% of the time you can get 90% of
```

2024-06-19 22:43 UTC, jazminite commented on src/interface/guide/foundation/FoundationCooldownSection.tsx
> +          The key idea is to <HL>use your cooldowns as many times as you can.</HL> For example: you
```suggestion
          The key idea is to <HL>use your cooldowns as many times as you can.</HL> For example, you
```

2024-06-19 22:43 UTC, jazminite commented on src/interface/guide/foundation/FoundationDowntimeSection.tsx
> +          The foundation of good play in <em>World of Warcraft</em> is having low downtime: step 1
```suggestion
          The foundation of good play in <em>World of Warcraft</em> is having low downtime.
```

2024-06-19 22:43 UTC, jazminite commented on src/interface/guide/foundation/FoundationDowntimeSection.tsx
> +          With practice, you will be able to both keep active and pick the right spells for each
```suggestion
          With practice, you can keep active and pick the right spells for each
```

2024-06-19 22:43 UTC, jazminite commented on src/interface/guide/foundation/FoundationDowntimeSection.tsx
> +        A good rule of thumb is that{' '}
```suggestion
        As a general guideline,{' '}
```

2024-06-19 22:43 UTC, jazminite commented on src/interface/guide/foundation/FoundationDowntimeSection.tsx
> +          to doing well is to <strong>Always Be Casting</strong>.{' '}
```suggestion
          The first step is to <strong>Always Be Casting (ABC)</strong>.{' '}
```

2024-06-20 17:48 UTC, emallson commented
those suggestions all look good. gonna make them locally so that prettier doesn't complain

2024-06-20 17:54 UTC, emallson commented
before merging this, i want to also implement it for a caster dps and a healer. gonna update the OP with a checklist

2024-06-21 02:37 UTC, jazminite approved these changes
Wording updates look good!

2024-06-26 18:18 UTC, merged