Add support for Cata Destruction Warlock
WoWAnalyzer/WoWAnalyzer pull request #6838
Opened 2024-06-21 20:54 UTC by emallson

This builds on the [foundation guide PR](https://github.com/WoWAnalyzer/WoWAnalyzer/pull/6832) to add support for Destro Lock in Cata Classic. As part of this, I also added a couple of other missing bits like the popular Synapse Springs engineering item and updated the potion cooldown to match the actual cooldown in-game (1m, only starts if used pre-combat).

Lastly, since this involved adding a number of new spells I also added a "copy definition" helper to the debug view to streamline that process a little bit. Not as nice as something auto-importing it, but much easier than entering it all by hand.

This includes the changes from #6832. I recommend checking [this diff](https://github.com/WoWAnalyzer/WoWAnalyzer/compare/emallson:WoWAnalyzer:foundation-guide-1...emallson:WoWAnalyzer:foundation/cata-destro) for easier viewing. (I can't target this PR at that branch because doing so puts the PR on my fork instead of the main fork where people have proper permissions)

## Screenshots

![image](https://github.com/WoWAnalyzer/WoWAnalyzer/assets/4909458/48ba3028-84a5-449e-b38a-8c578a11083d)
![image](https://github.com/WoWAnalyzer/WoWAnalyzer/assets/4909458/de7e2840-df2d-4cbd-b31d-605d7d275308)
![image](https://github.com/WoWAnalyzer/WoWAnalyzer/assets/4909458/ef8b2ed3-ab2d-4eef-b1c0-b9bb48961e06)

2024-06-23 01:25 UTC, jazminite requested changes
Mostly looks good!

2024-06-23 01:25 UTC, jazminite commented on src/analysis/classic/warlock/destruction/CHANGELOG.tsx
> +  // REMOVE THIS ENTRY AND ADD YOUR OWN
Remove comment

2024-06-23 01:25 UTC, jazminite commented on src/analysis/classic/warlock/destruction/modules/features/AlwaysBeCasting.tsx
> +            <SpellLink spell={SPELLS.FIRE_BLAST} /> or <SpellLink spell={SPELLS.ICE_LANCE} />.
Update these spells or remove the suggestion

2024-06-23 01:25 UTC, jazminite commented on src/analysis/classic/warlock/destruction/index.ts
> +// Reference this file in src\parser\index.ts
Remove comment

2024-06-25 03:44 UTC, jazminite approved these changes
Looks good!

2024-06-26 16:01 UTC, emallson commented
This has been merged into the main foundation guide PR

2024-06-26 16:01 UTC, closed without merging