[RSHAM] add statistic for nature's swiftness mana save
WoWAnalyzer/WoWAnalyzer pull request #6948
Opened 2024-08-13 18:23 UTC by Texleretour

### Description

Added a new Statistic to track mana saved from restoration shaman's talent Nature's Swiftness
Data is 10x'ed during prepatch due to new hardcoded mana cost values

2024-08-13 18:41 UTC, Texleretour commented
Resto shaman TWW support #6944 : Module in Statistics : Mana saved by Nature's swiftness

2024-08-13 20:26 UTC, Texleretour commented
![image](https://github.com/user-attachments/assets/ffc77171-6cc1-4c7f-93ba-0b33d1223a66)

2024-08-14 08:05 UTC, Krealle requested changes
Good first PR, just have a single comment.

2024-08-14 08:05 UTC, Krealle commented on src/analysis/retail/shaman/restoration/modules/talents/NaturesSwiftness.tsx
> +    }
This can be removed, the module won't run if `this.active` is false.

2024-08-14 08:21 UTC, Texleretour commented on src/analysis/retail/shaman/restoration/modules/talents/NaturesSwiftness.tsx
> +    }
okay thanks ! done

2024-08-14 08:37 UTC, Krealle approved these changes

2024-08-14 08:37 UTC, Krealle commented
LGTM

2024-08-14 14:04 UTC, merged