Eol attrib implementation
WoWAnalyzer/WoWAnalyzer pull request #7011
Opened 2024-09-10 03:03 UTC by Liavre

### Description

Implemented Echo of Light/Mastery spec wide so that modules are more accurate (previously there was no mastery attribution for heal amps or heals). The original Mastery module has only had its front facing stuff deleted, its TODO to rip out its backend stuff and replace it with the newer/more accurate module.

Unfortunately since mastery touches almost everything in the kit, this PR will be very long. likely the only mistakes made (if any, that I will also review after unscrambling my head from doing all this in one sitting session) is that I forgot a += and made it a = or I didn't update a talent icon in the tooltip when I was copy pasting.

2024-09-10 03:34 UTC, trevorm4 requested changes

2024-09-10 03:34 UTC, trevorm4 commented on src/analysis/retail/priest/holy/modules/core/EchoOfLightDisplay.tsx
> +    if (eolHeal === 0) {
```suggestion
    if (!eolHeal) {
```

2024-09-10 03:34 UTC, trevorm4 commented on src/analysis/retail/priest/holy/modules/core/EchoOfLightDisplay.tsx
> +            be updated in the back end blacklist. If there is a heal listed that shouldn't be please
```suggestion
            heals. This includes non spec direct heals such as enchants, trinkets, etc. <SpellLink spell=.../> SHOULD NOT proc on pet heals or HoTs. There can always be exceptions that have to
            be updated in the back end blacklist. If there is a heal listed that shouldn't be please
```

2024-09-10 03:34 UTC, trevorm4 commented on src/analysis/retail/priest/holy/modules/spells/HolyNova.tsx
> +   */
```suggestion
```

2024-09-10 03:34 UTC, trevorm4 commented on src/analysis/retail/priest/holy/modules/talents/Archon/EmpoweredSurgesHoly.tsx
> +            <ItemPercentHealingDone amount={this.eolContrib}></ItemPercentHealingDone> <br />
Instead of using `<br>`, wrap them in `<div>` instead as it renders better on all devices.

2024-09-10 03:34 UTC, trevorm4 commented on src/analysis/retail/priest/holy/modules/talents/Archon/PerfectedFormHoly.tsx
> +            + Apoth and contributes to Echo Of Light: <br />
Use SpellLink's here for salv/apoth/eol

2024-09-10 03:34 UTC, trevorm4 commented on src/analysis/retail/priest/holy/modules/talents/BottomRow/DivineWord.tsx
> +            Echo of Light procs from the initial Holy Word increase and all of the{' '}
use spellink for eol

2024-09-10 03:34 UTC, trevorm4 commented on src/analysis/retail/priest/holy/modules/talents/BottomRow/HolyWordSalvation.tsx
> +            this module due to the nature of Prayer of Mending. Find its direct initial heal
SpellLink for PoM

2024-09-10 03:34 UTC, trevorm4 commented on src/analysis/retail/priest/holy/modules/talents/BottomRow/ResonantWords.tsx
> +            {this.wastedResonantWords}/{this.totalResonantWords} wasted resonant word buffs.
Use SpellLink for Resonant Word

2024-09-10 03:34 UTC, trevorm4 commented on src/analysis/retail/priest/holy/modules/talents/MiddleRow/HealingChorus.tsx
> +            You gained ${this.totalStacks} stacks in total. ${overhealingTooltipString}% overhealing
The dollar sign shouldn't be necessary here since you're already in a tsx block

2024-09-10 03:34 UTC, trevorm4 commented on src/analysis/retail/priest/holy/modules/talents/Oracle/PremonitionOfPiety.tsx
> +            but it does redistribute any Echo of Light that overheals.
```suggestion
            but it does redistribute any Echo of Light that overheals.
```
use SpellLink

2024-09-10 20:25 UTC, Liavre commented
Tracking down a bug with calculations being off in some logs

2024-09-11 04:24 UTC, Liavre commented
After checking >20 live logs that all gave fairly accurate calculations, I just have to conclude that the PTR logs were just bugged.

2024-09-12 05:18 UTC, trevorm4 requested changes
2 small things and then we're good to go

2024-09-12 05:18 UTC, trevorm4 commented on src/analysis/retail/priest/holy/modules/talents/BottomRow/Lightwell.tsx
> +              Notably <SpellLink spell={SPELLS.RENEW_HEAL} /> does not contribute to Echo of Light.
```suggestion
              Notably <SpellLink spell={SPELLS.RENEW_HEAL} /> does not contribute to <SpellLink spell={SPELLS.ECHO_OF_LIGHT_MASTERY} />.
```

2024-09-12 05:18 UTC, trevorm4 commented on src/analysis/retail/priest/holy/modules/talents/MiddleRow/TrailOfLight.tsx
> +            <div>Trail of Light Procs: ${this.totalToLProcs}</div>
Use spell link

2024-09-12 06:45 UTC, trevorm4 approved these changes

2024-09-12 06:47 UTC, Liavre commented
Added in a small fix to some spells that don't include absorbed healing as effective healing (nerubar logs have exposed a lot of these).

2024-09-12 06:47 UTC, merged