Update MW for 11.0.5
WoWAnalyzer/WoWAnalyzer pull request #7150
Opened 2024-10-23 04:46 UTC by trevorm4

### Description

- Adds logic to use RWK if talented for many modules
- Deletes Nourishing Chi module
- Renames Ancient Teachings module to Jadefire Teachings

2024-10-23 12:09 UTC, vohrr requested changes

2024-10-23 12:09 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/core/apl/AplChoiceDescription.tsx
>          <SpellLink spell={talents.JADEFIRE_STOMP_TALENT} /> as often as necessary to maintain the{' '}
Or Thunder Focus Tea

2024-10-23 12:09 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/core/apl/AplChoiceDescription.tsx
> +        <SpellLink spell={talents.RISING_SUN_KICK_TALENT} />/
I don't suppose we could send PlayerInfo in here to use the getter from constants? So we don't need to do X/Y everywhere in the guide sections

2024-10-23 12:09 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/core/apl/AplChoiceDescription.tsx
> +        <SpellLink spell={talents.RISING_SUN_KICK_TALENT} />/
Same here

2024-10-23 12:09 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/features/MistweaverHealingEfficiencyDetails.tsx
> +                <SpellLink spell={TALENTS_MONK.RISING_MIST_TALENT} /> is given to{' '}
`JADEFIRE_TEACHINGS_TALENT`

2024-10-23 12:09 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/features/RisingMistBreakdown.tsx
> +        <SpellLink spell={getCurrentRSKTalent(this.selectedCombatant)} /> casts
Probably redundant but for readability  prefer this to be a const defined in the constructor 
`const rskTalent = getCurrentRSKTalent(this.selectedCombatant);`
etc
not a hill i'll die on tho

2024-10-23 12:09 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/features/TalentHealingStatistic.tsx
> +    if (this.selectedCombatant.hasTalent(TALENTS_MONK.RISING_MIST_TALENT)) {
`JADEFIRE_TEACHINGS_TALENT`

2024-10-23 12:09 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/constants.ts
> +    : SPELLS.RUSHING_WIND_KICK_DAMAGE;
`: SPELL.RISING_SUN_KICK_DAMAGE;`

2024-10-23 12:09 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/JadefireTeachings.tsx
> +   * After you cast Jadefire Stomp, Tiger Palm, Blackout Kick, and Rising Sun Kick heal an injured ally within 20 yards for 140% of the damage done. Lasts 15s.
Or TFT -- within 40yds -- an additional 140%

2024-10-23 12:09 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/JadefireTeachings.tsx
> +   * After you cast Jadefire Stomp, Tiger Palm, Blackout Kick, and Rising Sun Kick heal an injured ally within 20 yards for 140% of the damage done. Lasts 15s.
or alternatively remove this comment since we keep having to update it lol

2024-10-23 12:09 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/JadefireTeachings.tsx
> +    this.active = this.selectedCombatant.hasTalent(TALENTS_MONK.RISING_MIST_TALENT);
`JADEFIRE_TEACHINGS_TALENT`

2024-10-23 12:09 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/JadefireTeachings.tsx
> +          <SpellLink spell={TALENTS_MONK.RISING_MIST_TALENT} />
`JADEFIRE_TEACHINGS_TALENT`

2024-10-23 12:09 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/JadefireTeachings.tsx
> +            <SpellLink spell={TALENTS_MONK.RISING_MIST_TALENT} /> uptime
`JADEFIRE_TEACHINGS_TALENT`

2024-10-23 12:09 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/JadefireTeachings.tsx
> +        title={<SpellLink spell={TALENTS_MONK.RISING_MIST_TALENT} />}
`JADEFIRE_TEACHINGS_TALENT`

2024-10-23 12:09 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/JadefireTeachings.tsx
>    subStatistic() {
`JADEFIRE_TEACHINGS_TALENT`

2024-10-23 12:09 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/JadefireTeachings.tsx
> +      spells: [TALENTS_MONK.RISING_MIST_TALENT],
`JADEFIRE_TEACHINGS_TALENT`

2024-10-23 12:09 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/JadefireTeachings.tsx
> +            times without the <SpellLink spell={TALENTS_MONK.RISING_MIST_TALENT} /> buff active
`JADEFIRE_TEACHINGS_TALENT`

2024-10-23 12:09 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/JadefireTeachings.tsx
> +            <SpellLink spell={TALENTS_MONK.RISING_MIST_TALENT} /> -{' '}
`JADEFIRE_TEACHINGS_TALENT`

2024-10-23 12:09 UTC, vohrr commented on src/common/SPELLS/monk.ts
> +    name: 'Rising Sun Kick',
`Rushing Wind Kick`

2024-10-23 12:13 UTC, vohrr commented on src/analysis/retail/monk/mistweaver/modules/spells/UpliftedSpirits.tsx
> +      Events.damage.by(SELECTED_PLAYER).spell(getCurrentRSKTalentDamage(this.selectedCombatant)),
need to change this to  a cast event listener/handler - RWK gives cdr even if no targets are hit

2024-10-23 16:20 UTC, trevorm4 commented on src/analysis/retail/monk/mistweaver/modules/core/apl/AplChoiceDescription.tsx
> +        <SpellLink spell={talents.RISING_SUN_KICK_TALENT} />/
I tried but it was rather messy, can maybe try to do it in a future PR.

2024-10-24 14:36 UTC, vohrr approved these changes
LGTM, just the conflict with evoker changelog

2024-10-24 21:23 UTC, merged