Update Survival to 11.0.5
WoWAnalyzer/WoWAnalyzer pull request #7176
Opened 2024-11-11 07:02 UTC by Kivlov

### Description
Bringing Survival Hunter up to 11.0.5. There is a slew of changes that have not been implemented yet. I wanted to get this into a useable state in order to receive feedback from other Survival Players in the Trueshot Lodge discord.

Summary of reasoning for changes:
Wildfire Bomb now ignites and suggestions for overwriting debuff are suppressed.
Butchery is used in Single Target now to apply Merciless Blow. Modified statistics for Butchery.
Frenzied Strikes now provides 3s per target up to 15s hit.
Lunge, Kill Command, and Grenade Juggler all provide Wildfire Bomb cooldown reduction.
Flanking Strike is a spender now, not a generator.
ViperVenom talent applies serpent sting on raptor strike. Only useful metric is really uptime.

### Testing

https://www.warcraftlogs.com/reports/1c9HdABGLYnNXFjP#fight=31&type=damage-done&source=17
The above is one of my logs, Percival. All changes are universal to both hero trees, however Rashanaan was as Sentinel and the other bosses as Pack Leader.

- Screenshot(s):
![image](https://github.com/user-attachments/assets/117d4285-8a40-4cea-ab36-54a3cb948913)

2024-11-11 07:28 UTC, Kivlov commented on src/analysis/retail/hunter/shared/constants.ts
Added a MS_BUFFER_500 for Kill Command CDR.

2024-11-11 07:29 UTC, Kivlov commented on src/analysis/retail/hunter/shared/constants.ts
Constant for Kill Command CDR on Wildfire Bomb

2024-11-11 07:30 UTC, Kivlov commented on src/analysis/retail/hunter/survival/CONFIG.tsx
WoWhead writer is the Theorycrafter for Survival so didn't feel right not referencing their guide also.

2024-11-11 07:31 UTC, Kivlov commented on src/analysis/retail/hunter/survival/constants.ts
Tip can now be spent by any direct damaging ability. This didn't actually work when I tried to replace the RAPTOR_MONGOOSE_VARIANTS and forgot to remove it.

2024-11-11 21:25 UTC, Seriousnes requested changes
Good PR, just a few things to tidy up.

* Anything code that has been commented out should be deleted or the comments removed
* There are a few instances where you've left in a statistic method, but not returning anything. As I mentioned in one of the comments, remove it entirely if it's not useful any longer.

2024-11-11 21:25 UTC, Seriousnes commented on src/analysis/retail/hunter/survival/modules/talents/FlankingStrike.tsx
> +    // );
If these are no longer needed, they should be removed not commented out.

2024-11-11 21:25 UTC, Seriousnes commented on src/analysis/retail/hunter/survival/modules/talents/FlankingStrike.tsx
> +  // }
If these are no longer needed, they should be removed not commented out.

2024-11-11 21:25 UTC, Seriousnes commented on src/analysis/retail/hunter/survival/modules/talents/AlphaPredator.tsx
> +    // Not a particularly useful statistic so suppressing it. Talent is taken for the 2nd charge, not the damage.
Don't do this. If it's not needed, remove it entirely.

2024-11-11 21:25 UTC, Seriousnes commented on src/analysis/retail/hunter/survival/constants.ts
> +export const BOP_CA_EXTENSION_PER_CAST = 0;
If this interaction no longer exists, remove the constant.

2024-11-11 21:25 UTC, Seriousnes commented on src/analysis/retail/hunter/survival/constants.ts
> +export const FLANKING_STRIKE_FOCUS_GAIN = 0;
If this interaction no longer exists, remove the constant.

2024-11-11 21:25 UTC, Seriousnes commented on src/analysis/retail/hunter/survival/constants.ts
> +];
I don't see this being used, if it's not it can be removed.

2024-11-11 21:25 UTC, Seriousnes commented on src/analysis/retail/hunter/survival/modules/talents/FrenzyStrikes.tsx
> +    if (this.spellUsable.cooldownRemaining(spellId) < 3000) {
I'd recommend making this `3000` a constant, e.g. `FRENZY_STRIKES_CDR` or something similar

2024-11-11 21:25 UTC, Seriousnes commented on src/analysis/retail/hunter/survival/modules/talents/GrenadeJuggler.tsx
> +      this.wastedReductionMs += 2000;
Same thing, suggest making this `2000` a constant.

2024-11-11 21:25 UTC, Seriousnes commented on src/analysis/retail/hunter/survival/modules/talents/GrenadeJuggler.tsx
> + * Grenade Juggler reduces the remaining cooldown on Wildfire Bomb by 1.0 sec on auto-attack.
I think this comment is outdated. Grenade Juggler reduces the CD of Wildfire Bomb by 2 seconds when Explosive Shot is cast, not 1 second on auto-attack.

2024-11-11 21:25 UTC, Seriousnes commented on src/analysis/retail/hunter/survival/modules/talents/GuerrillaTactics.tsx
> +    // Talent is taken for the second charge, not the bomb damage.
If the statistic is no longer useful, remove the `statistic()` method entirely.

2024-11-12 01:41 UTC, Kivlov commented
Ok I think I have this ready to the point in terms of functionality that I would want to start to gather feedback from other SV players. Next steps would be to begin to set up the Guide instead of Suggestions.

2024-11-17 19:22 UTC, Pewtro approved these changes
Thanks for the PR! I think this looks fine if you could fix the conflicts :)

2024-11-18 16:17 UTC, merged